/**
 * Drawing Analysis Router
 *
 * ============================================================================
 * PRIME DIRECTIVE 2.0 COMPLIANCE
 * ============================================================================
 * §4.1  LLM BOUNDARY: extractDrawingData() = extractor only, evaluateCompliance() = judge only
 * §4.2  IMMUTABILITY: complianceAuditTrail is INSERT-ONLY, no UPDATE/DELETE
 * §4.3  STATUS WORKFLOW: DRAFT → UNDER_REVIEW → VALID | REJECTED
 * §6.1  ALL procedures use protectedProcedure (authentication required)
 * §6.3  DISCLAIMER: enforced at API layer before any analysis
 * §6.4  RESPONSE PAYLOAD: includes analysisStatus, disclaimerAcknowledged, llmModelVersion, ruleEngineVersion
 * §7.1  AUDIT TRAIL: all required fields populated on every event
 * §7.2  AUDIT EVENTS: all required action codes implemented
 * ============================================================================
 */

import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { protectedProcedure, publicProcedure, router } from "../_core/trpc";
import { getDb } from "../db";
import {
  drawingAnalyses,
  drawingDataExtractions,
  complianceEvaluationResults,
  complianceAuditTrail,
  disclaimerAcknowledgments,
  projects,
  drawingPages,
  detectedRooms,
  detectedFeatures,
  complianceResults,
} from "../../drizzle/schema";
import { eq, desc, and } from "drizzle-orm";
import { extractDrawingData, EXTRACTION_PROMPT_VERSION } from "../services/drawingExtractionService";
import { evaluateCompliance, RULE_ENGINE_VERSION } from "../services/drawingComplianceEngine";
import { storagePut } from "../storage";
import { preprocessDocument } from "../services/documentPreprocessingService";
import { queuePageAnalysis } from "../services/analysisQueue";
import { detectRoomsFromPage } from "../engine/spatial/roomDetectionService";
import crypto from "crypto";
import { extractIpAddress } from "../utils/extractIpAddress";

/**
 * Drizzle returns MySQL JSON columns as already-parsed objects.
 * Calling JSON.parse() on an object coerces it to "[object Object]" then fails.
 * This helper handles all three cases: object (pass through), string (parse),
 * falsy (return null).
 */
function safeJsonParse(value: unknown): unknown {
  if (!value) return null;
  if (typeof value === 'object') return value;
  if (typeof value === 'string') {
    try { return JSON.parse(value); } catch { return null; }
  }
  return null;
}

/** Feature flag: enables multi-page PDF preprocessing. Off by default to protect prod. */
const MULTI_PAGE_ENABLED = process.env.MULTI_PAGE_PDF === 'true';

/** Current disclaimer version — increment when disclaimer text changes (PD2.0 §8.1) */
export const CURRENT_DISCLAIMER_VERSION = "2.0";

/** Full disclaimer text stored with each acknowledgment (PD2.0 §8.1) */
const DISCLAIMER_TEXT = `IMPORTANT DISCLAIMER — Building Code Drawing Analysis Tool

This automated drawing analysis tool is provided for informational and preliminary review purposes ONLY.

1. NOT A PROFESSIONAL OPINION: The results generated by this tool do NOT constitute a professional engineering opinion, architectural review, or official building code compliance determination.

2. LLM LIMITATIONS: The AI extraction component identifies observable features from drawings. It may miss elements, misread dimensions, or fail to detect all relevant code provisions.

3. MANDATORY PROFESSIONAL REVIEW: All results MUST be reviewed and validated by a licensed professional engineer or registered architect before any regulatory submission, permit application, or construction activity.

4. NO LEGAL STANDING: Analysis results in DRAFT or UNDER_REVIEW status have NO legal standing and MUST NOT be used for regulatory submissions.

5. JURISDICTION VARIATIONS: Building code requirements vary by jurisdiction. This tool applies NBC (National Building Code of Canada) provisions only. Local amendments may apply.

6. USER RESPONSIBILITY: The user accepts full responsibility for verifying all results with a qualified professional.

By proceeding, you acknowledge that you have read, understood, and accept these terms.`;

// ============================================================================
// Audit Trail Helper (PD2.0 §7.1 — IMMUTABLE, INSERT-ONLY)
// ============================================================================

async function insertAuditEvent(params: {
  analysisId: number;
  userId: number;
  action: string;
  details: Record<string, unknown>;
  userEmail: string | null;
  userFullName?: string | null;
  professionalLicenseNumber?: string;
  professionalAssociation?: string;
  jurisdiction?: string;
  ipAddress?: string;
  userAgent?: string;
  sessionId?: string;
}) {
  const db = await getDb();
  if (!db) return;

  // PD2.0 §4.2: INSERT ONLY — never UPDATE or DELETE this table
  await db.insert(complianceAuditTrail).values({
    analysisId: params.analysisId,
    userId: params.userId,
    action: params.action,
    details: JSON.stringify(params.details),
    userEmail: params.userEmail ?? "",
    userFullName: params.userFullName ?? null,
    professionalLicenseNumber: params.professionalLicenseNumber ?? null,
    professionalAssociation: params.professionalAssociation ?? null,
    jurisdiction: params.jurisdiction ?? null,
    ipAddress: params.ipAddress ?? null,
    userAgent: params.userAgent ?? null,
    sessionId: params.sessionId ?? null,
    timestamp: new Date(),
  });
}

// ============================================================================
// Router
// ============================================================================

export const drawingAnalysisRouter = router({

  /**
   * Acknowledge disclaimer (PD2.0 §8.1)
   * Must be called before any analysis. Returns a token for the session.
   */
  acknowledgeDisclaimer: protectedProcedure
    .input(z.object({
      disclaimerVersion: z.string(),
    }))
    .mutation(async ({ input, ctx }) => {
      if (input.disclaimerVersion !== CURRENT_DISCLAIMER_VERSION) {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: `Disclaimer version mismatch. Expected ${CURRENT_DISCLAIMER_VERSION}, got ${input.disclaimerVersion}.`,
        });
      }

      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const ipAddress = extractIpAddress(ctx.req);
      const userAgent = ctx.req.headers["user-agent"] ?? "unknown";

      // Store acknowledgment record
      await db.insert(disclaimerAcknowledgments).values({
        userId: ctx.user.id,
        disclaimerVersion: CURRENT_DISCLAIMER_VERSION,
        disclaimerText: DISCLAIMER_TEXT,
        ipAddress,
        userAgent,
        acknowledgedAt: new Date(),
      });

      return {
        acknowledged: true,
        disclaimerVersion: CURRENT_DISCLAIMER_VERSION,
        acknowledgedAt: new Date().toISOString(),
      };
    }),

  /**
   * Get disclaimer text and current version
   */
  getDisclaimer: publicProcedure
    .query(() => ({
      version: CURRENT_DISCLAIMER_VERSION,
      text: DISCLAIMER_TEXT,
    })),

  /**
   * Check if the current user has already acknowledged the current disclaimer version.
   * Used to skip the disclaimer gate on subsequent visits.
   */
  checkDisclaimerStatus: protectedProcedure
    .query(async ({ ctx }) => {
      const db = await getDb();
      if (!db) return { hasAcknowledged: false, version: CURRENT_DISCLAIMER_VERSION };

      try {
        const [existing] = await db
          .select()
          .from(disclaimerAcknowledgments)
          .where(and(
            eq(disclaimerAcknowledgments.userId, ctx.user.id),
            eq(disclaimerAcknowledgments.disclaimerVersion, CURRENT_DISCLAIMER_VERSION),
          ))
          .limit(1);

        return {
          hasAcknowledged: !!existing,
          version: CURRENT_DISCLAIMER_VERSION,
        };
      } catch (error) {
        console.warn('[Disclaimer] checkDisclaimerStatus failed, defaulting to unacknowledged:', error);
        return { hasAcknowledged: false, version: CURRENT_DISCLAIMER_VERSION };
      }
    }),

  /**
   * Analyze a drawing — the main two-stage pipeline (PD2.0 §4.1)
   *
   * Stage 1: extractDrawingData() — LLM extracts structured data ONLY
   * Stage 2: evaluateCompliance() — deterministic engine evaluates rules ONLY
   *
   * All results persisted to DB with full audit trail.
   */
  analyze: protectedProcedure
    .input(z.object({
      projectId: z.number().int().positive(),
      imageBase64: z.string().min(1),
      mimeType: z.enum(["image/jpeg", "image/png", "image/webp", "image/gif", "application/pdf"]),
      fileName: z.string().min(1).max(255),
      analysisType: z.enum(["structural", "fire-safety", "connections", "comprehensive"]),
      analysisQuality: z.enum(["fast", "standard", "detailed"]).default("standard"),
      // PD2.0 §6.3: Disclaimer must be acknowledged before analysis
      disclaimerAcknowledged: z.literal(true, {
        error: "You must acknowledge the disclaimer before proceeding.",
      }),
      disclaimerVersion: z.string(),
    }))
    .mutation(async ({ input, ctx }) => {
      // PD2.0 §6.3: Enforce disclaimer at API layer
      if (!input.disclaimerVersion) {
        throw new TRPCError({
          code: "FORBIDDEN",
          message: "Disclaimer not acknowledged",
        });
      }
      if (input.disclaimerVersion !== CURRENT_DISCLAIMER_VERSION) {
        throw new TRPCError({
          code: "FORBIDDEN",
          message: `Disclaimer version mismatch. Please re-acknowledge the current disclaimer (v${CURRENT_DISCLAIMER_VERSION}).`,
        });
      }

      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const ipAddress = extractIpAddress(ctx.req);
      const userAgent = ctx.req.headers["user-agent"] ?? "unknown";
      const sessionId = ctx.req.headers["x-session-id"] as string | undefined;

      // PD2.0 §4.2: Compute SHA-256 hash of the image at upload time (immutable)
      const imageBuffer = Buffer.from(input.imageBase64, "base64");
      const drawingHash = crypto.createHash("sha256").update(imageBuffer).digest("hex");

      // Upload drawing snapshot to S3 for immutable storage
      let drawingUrl = "";
      let drawingSnapshotKey: string | null = null;
      try {
        const ext = input.mimeType.split("/")[1];
        const key = `drawing-analyses/${ctx.user.id}/${drawingHash}.${ext}`;
        const uploaded = await storagePut(key, imageBuffer, input.mimeType);
        drawingUrl = uploaded.url;
        drawingSnapshotKey = key;
      } catch (err) {
        console.error("[DrawingAnalysis] S3 upload failed:", err);
        // Continue without S3 — analysis can still proceed
        drawingUrl = `data:${input.mimeType};base64,${input.imageBase64.substring(0, 50)}...`;
      }

      // Create the analysis record in DRAFT status
      const insertResult = await db.insert(drawingAnalyses).values({
        projectId: input.projectId,
        userId: ctx.user.id,
        drawingUrl,
        drawingHash,
        drawingSnapshotKey,
        drawingSnapshotMimeType: input.mimeType,
        drawingSnapshotSize: imageBuffer.length,
        analysisType: input.analysisType,
        analysisStatus: "DRAFT",
        disclaimerAcknowledged: true,
        disclaimerAcknowledgedAt: new Date(),
        disclaimerVersion: CURRENT_DISCLAIMER_VERSION,
        ruleEngineVersion: RULE_ENGINE_VERSION,
      });

      const analysisId = insertResult[0].insertId;

      // PD2.0 §7.2: DRAWING_UPLOADED audit event
      await insertAuditEvent({
        analysisId,
        userId: ctx.user.id,
        action: "DRAWING_UPLOADED",
        details: {
          fileName: input.fileName,
          mimeType: input.mimeType,
          fileSize: imageBuffer.length,
          drawingHash,
          analysisType: input.analysisType,
          disclaimerVersion: CURRENT_DISCLAIMER_VERSION,
        },
        userEmail: ctx.user.email,
        userFullName: ctx.user.name ?? null,
        ipAddress,
        userAgent,
        sessionId,
      });

      // PD2.0 §7.2: ANALYSIS_INITIATED audit event
      await insertAuditEvent({
        analysisId,
        userId: ctx.user.id,
        action: "ANALYSIS_INITIATED",
        details: { analysisType: input.analysisType, promptVersion: EXTRACTION_PROMPT_VERSION },
        userEmail: ctx.user.email,
        userFullName: ctx.user.name ?? null,
        ipAddress,
        userAgent,
        sessionId,
      });

      // ======================================================================
      // PDF PRE-PROCESSING (MULTI_PAGE_ENABLED guard)
      // Rasterizes pages, uploads to storage, records drawingPages rows.
      // When flag is off, PDF uploads are rejected early — Claude Vision
      // cannot process raw PDF bytes, so there is no fallback single-image path.
      // ======================================================================

      let page1Base64 = input.imageBase64;
      let page1MimeType: string = input.mimeType;
      let pageCount = 1;
      // Holds the preprocessed result so room detection can use it later
      let pdfPreprocessed: Awaited<ReturnType<typeof preprocessDocument>> | null = null;

      if (input.mimeType === "application/pdf") {
        if (!MULTI_PAGE_ENABLED) {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message: "Multi-page PDF analysis is not yet enabled. Please upload a JPEG, PNG, or WebP image.",
          });
        }
        try {
          pdfPreprocessed = await preprocessDocument(analysisId, ctx.user.id, imageBuffer);
          pageCount = pdfPreprocessed.pageCount;
          if (pdfPreprocessed.pages.length > 0) {
            page1Base64 = pdfPreprocessed.pages[0].base64;
            page1MimeType = pdfPreprocessed.pages[0].mimeType;
          }
        } catch (err) {
          console.error("[DrawingAnalysis] PDF preprocessing failed:", err);
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "PDF preprocessing failed. Please ensure the file is a valid, non-encrypted PDF.",
          });
        }
      }

      // ======================================================================
      // STAGE 1: LLM Extraction (PD2.0 §4.1 — extractor ONLY)
      // ======================================================================

      // Fetch project context to enrich the extraction prompt
      let projectContext: { occupancyCode?: string; province?: string; buildingType?: string } | undefined;
      try {
        const [proj] = await db
          .select({ occupancyCode: projects.occupancyCode, province: projects.province, buildingType: projects.buildingType })
          .from(projects)
          .where(eq(projects.id, input.projectId))
          .limit(1);
        if (proj) {
          projectContext = {
            occupancyCode: proj.occupancyCode ?? undefined,
            province: proj.province ?? undefined,
            buildingType: proj.buildingType ?? undefined,
          };
        }
      } catch {
        // Non-critical — proceed without context
      }

      let extractionResult;
      let modelVersion = "unknown";
      try {
        const extracted = await queuePageAnalysis(() => extractDrawingData(
          page1Base64,
          page1MimeType,
          input.analysisType,
          input.analysisQuality,
          projectContext,
        ));
        extractionResult = extracted.data;
        modelVersion = extracted.modelVersion;

        // Persist extraction result (PD2.0 §4.1: LLM output stored separately)
        await db.insert(drawingDataExtractions).values({
          analysisId,
          extractedData: JSON.stringify(extractionResult),
          extractionModel: modelVersion,
          extractionPromptVersion: EXTRACTION_PROMPT_VERSION,
          extractionConfidence: String(
            extractionResult.structural?.confidence ??
            extractionResult.fireSafety?.confidence ??
            extractionResult.connections?.confidence ??
            0.5
          ) as any,
          extractedAt: new Date(),
        });

        // PD2.0 §7.2: EXTRACTION_COMPLETED audit event
        await insertAuditEvent({
          analysisId,
          userId: ctx.user.id,
          action: "EXTRACTION_COMPLETED",
          details: {
            modelVersion,
            promptVersion: EXTRACTION_PROMPT_VERSION,
            drawingType: extractionResult.drawingType,
            structuralMembersFound: extractionResult.structural?.memberSizes?.length ?? 0,
            fireSafetyExitsFound: extractionResult.fireSafety?.exitWidths?.length ?? 0,
            connectionsFound: extractionResult.connections?.fastenerTypes?.length ?? 0,
          },
          userEmail: ctx.user.email,
          userFullName: ctx.user.name ?? null,
          ipAddress,
          userAgent,
          sessionId,
        });
      } catch (err) {
        console.error("[DrawingAnalysis] Stage 1 extraction failed:", err);
        // Update analysis to reflect failure
        await db.update(drawingAnalyses)
          .set({ analysisStatus: "REJECTED", llmModelVersion: "error" })
          .where(eq(drawingAnalyses.id, analysisId));
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Drawing extraction failed. Please try again with a clearer image.",
        });
      }

      // ======================================================================
      // STAGE 2: Deterministic Compliance Evaluation (PD2.0 §4.1 — judge ONLY)
      // ======================================================================
      const engineOutput = evaluateCompliance(extractionResult);

      // Persist each rule evaluation result
      for (const ruleEval of engineOutput.ruleEvaluations) {
        await db.insert(complianceEvaluationResults).values({
          analysisId,
          ruleId: 0, // No FK to nbcRules table yet — use 0 as placeholder
          ruleVersion: 1,
          evaluationResult: ruleEval.result,
          evaluationDetails: JSON.stringify({
            ruleId: ruleEval.ruleId,
            clause: ruleEval.clause,
            description: ruleEval.description,
            category: ruleEval.category,
            severity: ruleEval.severity,
            details: ruleEval.details,
          }),
          evaluatedAt: new Date(),
        });
      }

      // PD2.0 §7.2: EVALUATION_COMPLETED audit event
      await insertAuditEvent({
        analysisId,
        userId: ctx.user.id,
        action: "EVALUATION_COMPLETED",
        details: {
          ruleEngineVersion: RULE_ENGINE_VERSION,
          rulesEvaluated: engineOutput.ruleEvaluations.length,
          passCount: engineOutput.ruleEvaluations.filter(r => r.result === "PASS").length,
          failCount: engineOutput.ruleEvaluations.filter(r => r.result === "FAIL").length,
          conditionalCount: engineOutput.ruleEvaluations.filter(r => r.result === "CONDITIONAL").length,
          unableCount: engineOutput.ruleEvaluations.filter(r => r.result === "UNABLE_TO_EVALUATE").length,
        },
        userEmail: ctx.user.email,
        userFullName: ctx.user.name ?? null,
        ipAddress,
        userAgent,
        sessionId,
      });

      // PD2.0 §7.2: SCORE_CALCULATED audit event
      await insertAuditEvent({
        analysisId,
        userId: ctx.user.id,
        action: "SCORE_CALCULATED",
        details: {
          complianceScore: engineOutput.complianceScore,
          complianceLevel: engineOutput.complianceLevel,
          issueCount: engineOutput.issues.length,
          recommendationCount: engineOutput.recommendations.length,
        },
        userEmail: ctx.user.email,
        userFullName: ctx.user.name ?? null,
        ipAddress,
        userAgent,
        sessionId,
      });

      // Update the analysis record with results — status moves to UNDER_REVIEW (PD2.0 §4.3)
      try {
        await db.update(drawingAnalyses).set({
          analysisStatus: "UNDER_REVIEW",
          complianceScore: engineOutput.complianceScore,
          complianceLevel: engineOutput.complianceLevel,
          structuralStatus: JSON.stringify(extractionResult.structural ?? {}),
          fireSafetyStatus: JSON.stringify(extractionResult.fireSafety ?? {}),
          connectionStatus: JSON.stringify(extractionResult.connections ?? {}),
          issues: JSON.stringify(engineOutput.issues),
          recommendations: JSON.stringify(engineOutput.recommendations),
          llmModelVersion: modelVersion,
          ruleEngineVersion: RULE_ENGINE_VERSION,
          updatedAt: new Date(),
        }).where(eq(drawingAnalyses.id, analysisId));
      } catch (updateError) {
        console.error('[DrawingAnalysis] UPDATE failed (non-fatal):', JSON.stringify({
          message: (updateError as any)?.message,
          code: (updateError as any)?.code,
          sqlMessage: (updateError as any)?.cause?.sqlMessage,
          sql: (updateError as any)?.cause?.sql?.substring(0, 200),
        }));
        // Continue — don't throw, results still returned to client
      }

      // ======================================================================
      // ROOM DETECTION — non-blocking, runs after main analysis completes
      // ======================================================================

      // PDF path: room detection from rasterized page 1
      if (pdfPreprocessed && pdfPreprocessed.pages.length > 0) {
        const page1b64 = pdfPreprocessed.pages[0].base64;
        // Look up the drawingPages row inserted during preprocessing
        db.select()
          .from(drawingPages)
          .where(and(eq(drawingPages.drawingId, analysisId), eq(drawingPages.pageNumber, 1)))
          .limit(1)
          .then(([page1Record]) => {
            if (!page1Record) return;
            console.log('[RoomDetection] Queuing room detection for page', page1Record.id);
            return queuePageAnalysis(() =>
              detectRoomsFromPage(page1b64, page1Record.id, input.projectId, 1, projectContext)
            );
          })
          .catch(err => console.error('[RoomDetection] PDF page 1 detection failed:', err));
      }

      // Single-image path: create a synthetic drawingPage row, then detect
      if (input.mimeType !== "application/pdf") {
        db.insert(drawingPages).values({
          drawingId: analysisId,
          pageNumber: 1,
          widthPx: 0,
          heightPx: 0,
          preprocessedUrl: drawingUrl || null,
        })
          .then(result => {
            const syntheticPageId = result[0].insertId;
            console.log('[RoomDetection] Queuing room detection for page', syntheticPageId);
            return queuePageAnalysis(() =>
              detectRoomsFromPage(input.imageBase64, syntheticPageId, input.projectId, 1, projectContext)
            );
          })
          .catch(err => console.error('[RoomDetection] Image detection failed:', err));
      }

      // PD2.0 §6.4: Response payload must include all required fields
      return {
        analysisId,
        analysisStatus: "UNDER_REVIEW" as const,
        disclaimerAcknowledged: true,
        disclaimerVersion: CURRENT_DISCLAIMER_VERSION,
        llmModelVersion: modelVersion,
        ruleEngineVersion: RULE_ENGINE_VERSION,
        pageCount,
        complianceScore: engineOutput.complianceScore,
        complianceLevel: engineOutput.complianceLevel,
        ruleEvaluations: engineOutput.ruleEvaluations,
        issues: engineOutput.issues,
        recommendations: engineOutput.recommendations,
        extractedData: {
          drawingType: extractionResult.drawingType,
          jurisdiction: extractionResult.jurisdiction,
          structural: extractionResult.structural,
          fireSafety: extractionResult.fireSafety,
          connections: extractionResult.connections,
        },
      };
    }),

  /**
   * Get analysis by ID (PD2.0 §7.2: ANALYSIS_VIEWED audit event)
   */
  getAnalysis: protectedProcedure
    .input(z.object({ analysisId: z.number().int().positive() }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const [analysis] = await db
        .select()
        .from(drawingAnalyses)
        .where(and(
          eq(drawingAnalyses.id, input.analysisId),
          eq(drawingAnalyses.userId, ctx.user.id)
        ));

      if (!analysis) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Analysis not found" });
      }

      // PD2.0 §7.2: ANALYSIS_VIEWED audit event (INSERT-ONLY)
      await insertAuditEvent({
        analysisId: input.analysisId,
        userId: ctx.user.id,
        action: "ANALYSIS_VIEWED",
        details: { analysisStatus: analysis.analysisStatus },
        userEmail: ctx.user.email,
        userFullName: ctx.user.name ?? null,
        ipAddress: extractIpAddress(ctx.req),
        userAgent: ctx.req.headers["user-agent"] ?? "unknown",
      });

      return {
        ...analysis,
        // PD2.0 §6.4: Always include required fields
        disclaimerAcknowledged: analysis.disclaimerAcknowledged,
        disclaimerVersion: analysis.disclaimerVersion,
        llmModelVersion: analysis.llmModelVersion,
        ruleEngineVersion: analysis.ruleEngineVersion,
        analysisStatus: analysis.analysisStatus,
      };
    }),

  /**
   * List analyses for a project
   */
  listByProject: protectedProcedure
    .input(z.object({ projectId: z.number().int().positive() }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const analyses = await db
        .select()
        .from(drawingAnalyses)
        .where(and(
          eq(drawingAnalyses.projectId, input.projectId),
          eq(drawingAnalyses.userId, ctx.user.id)
        ))
        .orderBy(desc(drawingAnalyses.createdAt));

      return analyses;
    }),

  /**
   * Get audit trail for an analysis (read-only view)
   */
  getAuditTrail: protectedProcedure
    .input(z.object({ analysisId: z.number().int().positive() }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      // Verify ownership
      const [analysis] = await db
        .select({ id: drawingAnalyses.id })
        .from(drawingAnalyses)
        .where(and(
          eq(drawingAnalyses.id, input.analysisId),
          eq(drawingAnalyses.userId, ctx.user.id)
        ));

      if (!analysis) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Analysis not found" });
      }

      const trail = await db
        .select()
        .from(complianceAuditTrail)
        .where(eq(complianceAuditTrail.analysisId, input.analysisId))
        .orderBy(complianceAuditTrail.timestamp);

      return trail;
    }),

  /**
   * Professional validation — transitions UNDER_REVIEW → VALID (PD2.0 §4.3)
   * Only accessible to authenticated users with professional credentials
   */
  validateAnalysis: protectedProcedure
    .input(z.object({
      analysisId: z.number().int().positive(),
      licenseNumber: z.string().min(1).max(100),
      professionalAssociation: z.string().min(1).max(100),
      jurisdiction: z.string().min(1).max(100),
      validationNotes: z.string().max(2000).optional(),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const [analysis] = await db
        .select()
        .from(drawingAnalyses)
        .where(and(
          eq(drawingAnalyses.id, input.analysisId),
          eq(drawingAnalyses.userId, ctx.user.id)
        ));

      if (!analysis) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Analysis not found" });
      }

      // PD2.0 §4.3: Only UNDER_REVIEW analyses can be validated
      if (analysis.analysisStatus !== "UNDER_REVIEW") {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: `Cannot validate analysis in status '${analysis.analysisStatus}'. Only UNDER_REVIEW analyses can be validated.`,
        });
      }

      // Transition to VALID
      await db.update(drawingAnalyses).set({
        analysisStatus: "VALID",
        validatedAt: new Date(),
        validatedByUserId: ctx.user.id,
        validatedByLicenseNumber: input.licenseNumber,
        validatedByAssociation: input.professionalAssociation,
        updatedAt: new Date(),
      }).where(eq(drawingAnalyses.id, input.analysisId));

      // PD2.0 §7.2: PROFESSIONAL_ACCEPTED + SIGNATURE_APPLIED (single transaction)
      await insertAuditEvent({
        analysisId: input.analysisId,
        userId: ctx.user.id,
        action: "PROFESSIONAL_ACCEPTED",
        details: {
          licenseNumber: input.licenseNumber,
          association: input.professionalAssociation,
          jurisdiction: input.jurisdiction,
          notes: input.validationNotes ?? null,
          validatedAt: new Date().toISOString(),
        },
        userEmail: ctx.user.email,
        userFullName: ctx.user.name ?? null,
        professionalLicenseNumber: input.licenseNumber,
        professionalAssociation: input.professionalAssociation,
        jurisdiction: input.jurisdiction,
        ipAddress: extractIpAddress(ctx.req),
        userAgent: ctx.req.headers["user-agent"] ?? "unknown",
      });

      return { success: true, analysisStatus: "VALID" as const };
    }),

  /**
   * Export compliance report as structured JSON for PDF generation (PD2.0 §9.1)
   * Only available for VALID-status analyses.
   * The client uses this data to generate a PDF report.
   */
  exportReport: protectedProcedure
    .input(z.object({
      analysisId: z.number().int().positive(),
    }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const [analysis] = await db
        .select()
        .from(drawingAnalyses)
        .where(and(
          eq(drawingAnalyses.id, input.analysisId),
          eq(drawingAnalyses.userId, ctx.user.id)
        ));

      if (!analysis) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Analysis not found" });
      }

      // PD2.0 §9.1: Only VALID analyses can be exported
      if (analysis.analysisStatus !== "VALID") {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: `Only VALID analyses can be exported. Current status: ${analysis.analysisStatus}`,
        });
      }

      // Fetch audit trail for the report
      const auditTrail = await db
        .select()
        .from(complianceAuditTrail)
        .where(eq(complianceAuditTrail.analysisId, input.analysisId))
        .orderBy(complianceAuditTrail.timestamp);

      // PD2.0 §7.2: REPORT_EXPORTED audit event
      await insertAuditEvent({
        analysisId: input.analysisId,
        userId: ctx.user.id,
        action: "REPORT_EXPORTED",
        details: { exportFormat: "pdf", exportedAt: new Date().toISOString() },
        userEmail: ctx.user.email,
        userFullName: ctx.user.name ?? null,
        ipAddress: extractIpAddress(ctx.req),
        userAgent: ctx.req.headers["user-agent"] ?? "unknown",
      });

      // Find the PROFESSIONAL_ACCEPTED event for reviewer info
      const professionalEvent = auditTrail.find(e => e.action === "PROFESSIONAL_ACCEPTED");

      return {
        analysisId: analysis.id,
        analysisStatus: analysis.analysisStatus,
        analysisType: analysis.analysisType,
        complianceScore: analysis.complianceScore,
        complianceLevel: analysis.complianceLevel,
        issues: analysis.issues ? JSON.parse(analysis.issues as string) : [],
        recommendations: analysis.recommendations ? JSON.parse(analysis.recommendations as string) : [],
        llmModelVersion: analysis.llmModelVersion,
        ruleEngineVersion: analysis.ruleEngineVersion,
        disclaimerVersion: analysis.disclaimerVersion,
        createdAt: analysis.createdAt,
        validatedAt: analysis.validatedAt,
        validatedByLicenseNumber: analysis.validatedByLicenseNumber,
        validatedByAssociation: analysis.validatedByAssociation,
        reviewerName: ctx.user.name,
        reviewerEmail: ctx.user.email,
        // Audit trail summary
        auditTrailSummary: auditTrail.map(e => ({
          action: e.action,
          timestamp: e.timestamp,
          userEmail: e.userEmail,
          details: typeof e.details === "string" ? JSON.parse(e.details) : e.details,
        })),
        // Professional event details
        professionalDetails: professionalEvent ? {
          licenseNumber: professionalEvent.professionalLicenseNumber,
          association: professionalEvent.professionalAssociation,
          jurisdiction: professionalEvent.jurisdiction,
          notes: (typeof professionalEvent.details === "string"
            ? JSON.parse(professionalEvent.details)
            : professionalEvent.details)?.notes ?? null,
        } : null,
      };
    }),

  /**
   * Reject analysis — transitions UNDER_REVIEW → REJECTED (PD2.0 §4.3)
   */
  rejectAnalysis: protectedProcedure
    .input(z.object({
      analysisId: z.number().int().positive(),
      rejectionReason: z.string().min(1).max(2000),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const [analysis] = await db
        .select()
        .from(drawingAnalyses)
        .where(and(
          eq(drawingAnalyses.id, input.analysisId),
          eq(drawingAnalyses.userId, ctx.user.id)
        ));

      if (!analysis) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Analysis not found" });
      }

      if (analysis.analysisStatus !== "UNDER_REVIEW") {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: `Cannot reject analysis in status '${analysis.analysisStatus}'.`,
        });
      }

      await db.update(drawingAnalyses).set({
        analysisStatus: "REJECTED",
        updatedAt: new Date(),
      }).where(eq(drawingAnalyses.id, input.analysisId));

      // PD2.0 §7.2: PROFESSIONAL_REJECTED audit event
      await insertAuditEvent({
        analysisId: input.analysisId,
        userId: ctx.user.id,
        action: "PROFESSIONAL_REJECTED",
        details: { rejectionReason: input.rejectionReason },
        userEmail: ctx.user.email,
        userFullName: ctx.user.name ?? null,
        ipAddress: extractIpAddress(ctx.req),
        userAgent: ctx.req.headers["user-agent"] ?? "unknown",
      });

      return { success: true, analysisStatus: "REJECTED" as const };
    }),

  /**
   * Get all detected rooms and features for a drawing (all pages)
   */
  getRoomsForDrawing: protectedProcedure
    .input(z.object({ drawingId: z.number().int().positive() }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      // Verify ownership
      const [analysis] = await db
        .select({ id: drawingAnalyses.id })
        .from(drawingAnalyses)
        .where(and(eq(drawingAnalyses.id, input.drawingId), eq(drawingAnalyses.userId, ctx.user.id)));

      if (!analysis) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Drawing not found" });
      }

      const pages = await db
        .select()
        .from(drawingPages)
        .where(eq(drawingPages.drawingId, input.drawingId));

      const rooms = [];
      for (const page of pages) {
        const pageRooms = await db
          .select()
          .from(detectedRooms)
          .where(eq(detectedRooms.pageId, page.id));

        for (const room of pageRooms) {
          const features = await db
            .select()
            .from(detectedFeatures)
            .where(eq(detectedFeatures.roomId, room.id));

          rooms.push({
            ...room,
            boundingBox: safeJsonParse(room.boundingBoxJson),
            flags: (safeJsonParse(room.flagsJson) as any[]) ?? [],
            features: features.map(f => ({
              ...f,
              position: safeJsonParse(f.positionJson),
              metadata: safeJsonParse(f.metadataJson),
            })),
          });
        }
      }

      console.log('[RoomQuery] returning', rooms.length, 'rooms for drawingId', input.drawingId);
      return { pages, rooms };
    }),

  /**
   * Get per-room compliance results for a project
   */
  getRoomCompliance: protectedProcedure
    .input(z.object({
      drawingId: z.number(),
      projectId: z.number()
    }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: 'DB unavailable' });

      const rooms = await db
        .select()
        .from(detectedRooms)
        .where(eq(detectedRooms.projectId, input.projectId));

      const results = [];
      for (const room of rooms) {
        const compliance = await db
          .select()
          .from(complianceResults)
          .where(eq(complianceResults.roomId, room.id));

        results.push({
          room: {
            ...room,
            boundingBox: safeJsonParse(room.boundingBoxJson),
          },
          compliance,
        });
      }

      return results;
    }),
});
