/**
 * Drawing Analysis Router
 *
 * ============================================================================
 * PRIME DIRECTIVE 2.0 COMPLIANCE
 * ============================================================================
 * §4.1  LLM BOUNDARY: extractDrawingData() = extractor only, evaluateCompliance() = judge only
 * §4.2  IMMUTABILITY: complianceAuditTrail is INSERT-ONLY, no UPDATE/DELETE
 * §4.3  STATUS WORKFLOW: DRAFT → UNDER_REVIEW → VALID | REJECTED
 * §6.1  ALL procedures use protectedProcedure (authentication required)
 * §6.3  DISCLAIMER: enforced at API layer before any analysis
 * §6.4  RESPONSE PAYLOAD: includes analysisStatus, disclaimerAcknowledged, llmModelVersion, ruleEngineVersion
 * §7.1  AUDIT TRAIL: all required fields populated on every event
 * §7.2  AUDIT EVENTS: all required action codes implemented
 * ============================================================================
 */

import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { protectedProcedure, publicProcedure, router } from "../_core/trpc";
import { getDb } from "../db";
import {
  drawingAnalyses,
  drawingDataExtractions,
  complianceEvaluationResults,
  complianceAuditTrail,
  disclaimerAcknowledgments,
  projects,
  drawingPages,
  measuredWindows,
  sitePlanExtractions,
  detectedRooms,
  detectedFeatures,
  complianceResults,
  users,
} from "../../drizzle/schema";
import { eq, desc, and } from "drizzle-orm";
import { extractDrawingData, EXTRACTION_PROMPT_VERSION } from "../services/drawingExtractionService";
import { evaluateCompliance, RULE_ENGINE_VERSION } from "../services/drawingComplianceEngine";
import { calculateTravelDistances } from "../services/travelDistanceService";
import { computeRoomAdjacency } from "../services/adjacencyService";
import { storagePut } from "../storage";
import { preprocessDocument } from "../services/documentPreprocessingService";
import { queuePageAnalysis } from "../services/analysisQueue";
import { detectRoomsFromPage } from "../engine/spatial/roomDetectionService";
import type { DrawingType } from "../engine/spatial/promptLibrary";
import crypto from "crypto";
import { extractIpAddress } from "../utils/extractIpAddress";
import { runWallEngine } from "../services/wallEngineOrchestrator";
import { wallEngineQueue } from "../services/wallEngineQueue";
import { runCalculatorOrchestrator } from "../services/calculatorOrchestrator";
import { persistRequirementGraph } from "../services/complianceRequirementGraph";
import { readProvenancedFact, userConfirmedFact } from "../services/factProvenance";
import { callAnthropicVision } from "../services/anthropicVisionService";
import {
  buildSitePlanPrompts,
  deriveLotCoveragePct,
  SitePlanExtractionSchema,
} from "../services/sitePlanExtractionService";

/**
 * Drizzle returns MySQL JSON columns as already-parsed objects.
 * Calling JSON.parse() on an object coerces it to "[object Object]" then fails.
 * This helper handles all three cases: object (pass through), string (parse),
 * falsy (return null).
 */
function safeJsonParse(value: unknown): unknown {
  if (!value) return null;
  if (typeof value === 'object') return value;
  if (typeof value === 'string') {
    try { return JSON.parse(value); } catch { return null; }
  }
  return null;
}

function normalizeRoomFacts(room: any) {
  const area = readProvenancedFact({ wrapper: room.areaSqmJson, scalar: room.areaSqm == null ? null : Number(room.areaSqm), field: 'areaSqm', entityType: 'room', entityId: room.id, isValue: (v): v is number => typeof v === 'number' && Number.isFinite(v) && v >= 0 }).value;
  const occupancy = readProvenancedFact({ wrapper: room.occupancyGroupJson, scalar: room.occupancyGroup, field: 'occupancyGroup', entityType: 'room', entityId: room.id, isValue: (v): v is string => typeof v === 'string' && v.length > 0 }).value;
  return { ...room, areaSqm: area == null ? room.areaSqm : area.toFixed(2), occupancyGroup: occupancy ?? room.occupancyGroup };
}

/** Feature flag: enables multi-page PDF preprocessing. Off by default to protect prod. */
const MULTI_PAGE_ENABLED = process.env.MULTI_PAGE_PDF === 'true';

/** Current disclaimer version — increment when disclaimer text changes (PD2.0 §8.1) */
export const CURRENT_DISCLAIMER_VERSION = "2.0";

/** Full disclaimer text stored with each acknowledgment (PD2.0 §8.1) */
const DISCLAIMER_TEXT = `IMPORTANT DISCLAIMER — Building Code Drawing Analysis Tool

This automated drawing analysis tool is provided for informational and preliminary review purposes ONLY.

1. NOT A PROFESSIONAL OPINION: The results generated by this tool do NOT constitute a professional engineering opinion, architectural review, or official building code compliance determination.

2. LLM LIMITATIONS: The AI extraction component identifies observable features from drawings. It may miss elements, misread dimensions, or fail to detect all relevant code provisions.

3. MANDATORY PROFESSIONAL REVIEW: All results MUST be reviewed and validated by a licensed professional engineer or registered architect before any regulatory submission, permit application, or construction activity.

4. NO LEGAL STANDING: Analysis results in DRAFT or UNDER_REVIEW status have NO legal standing and MUST NOT be used for regulatory submissions.

5. JURISDICTION VARIATIONS: Building code requirements vary by jurisdiction. This tool applies NBC (National Building Code of Canada) provisions only. Local amendments may apply.

6. USER RESPONSIBILITY: The user accepts full responsibility for verifying all results with a qualified professional.

By proceeding, you acknowledge that you have read, understood, and accept these terms.`;

// ============================================================================
// Audit Trail Helper (PD2.0 §7.1 — IMMUTABLE, INSERT-ONLY)
// ============================================================================

async function insertAuditEvent(params: {
  analysisId: number;
  userId: number;
  action: string;
  details: Record<string, unknown>;
  userEmail: string | null;
  userFullName?: string | null;
  professionalLicenseNumber?: string;
  professionalAssociation?: string;
  jurisdiction?: string;
  ipAddress?: string;
  userAgent?: string;
  sessionId?: string;
}) {
  const db = await getDb();
  if (!db) return;

  // PD2.0 §4.2: INSERT ONLY — never UPDATE or DELETE this table
  await db.insert(complianceAuditTrail).values({
    analysisId: params.analysisId,
    userId: params.userId,
    action: params.action,
    details: JSON.stringify(params.details),
    userEmail: params.userEmail ?? "",
    userFullName: params.userFullName ?? null,
    professionalLicenseNumber: params.professionalLicenseNumber ?? null,
    professionalAssociation: params.professionalAssociation ?? null,
    jurisdiction: params.jurisdiction ?? null,
    ipAddress: params.ipAddress ?? null,
    userAgent: params.userAgent ?? null,
    sessionId: params.sessionId ?? null,
    timestamp: new Date(),
  });
}

// ============================================================================
// Router
// ============================================================================

export const drawingAnalysisRouter = router({

  /**
   * Acknowledge disclaimer (PD2.0 §8.1)
   * Must be called before any analysis. Returns a token for the session.
   */
  acknowledgeDisclaimer: protectedProcedure
    .input(z.object({
      disclaimerVersion: z.string(),
    }))
    .mutation(async ({ input, ctx }) => {
      if (input.disclaimerVersion !== CURRENT_DISCLAIMER_VERSION) {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: `Disclaimer version mismatch. Expected ${CURRENT_DISCLAIMER_VERSION}, got ${input.disclaimerVersion}.`,
        });
      }

      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const ipAddress = extractIpAddress(ctx.req);
      const userAgent = ctx.req.headers["user-agent"] ?? "unknown";

      // Store acknowledgment record
      await db.insert(disclaimerAcknowledgments).values({
        userId: ctx.user.id,
        disclaimerVersion: CURRENT_DISCLAIMER_VERSION,
        disclaimerText: DISCLAIMER_TEXT,
        ipAddress,
        userAgent,
        acknowledgedAt: new Date(),
      });

      return {
        acknowledged: true,
        disclaimerVersion: CURRENT_DISCLAIMER_VERSION,
        acknowledgedAt: new Date().toISOString(),
      };
    }),

  /**
   * Get disclaimer text and current version
   */
  getDisclaimer: publicProcedure
    .query(() => ({
      version: CURRENT_DISCLAIMER_VERSION,
      text: DISCLAIMER_TEXT,
    })),

  /**
   * Check if the current user has already acknowledged the current disclaimer version.
   * Used to skip the disclaimer gate on subsequent visits.
   */
  checkDisclaimerStatus: protectedProcedure
    .query(async ({ ctx }) => {
      const db = await getDb();
      if (!db) return { hasAcknowledged: false, version: CURRENT_DISCLAIMER_VERSION };

      try {
        const [existing] = await db
          .select()
          .from(disclaimerAcknowledgments)
          .where(and(
            eq(disclaimerAcknowledgments.userId, ctx.user.id),
            eq(disclaimerAcknowledgments.disclaimerVersion, CURRENT_DISCLAIMER_VERSION),
          ))
          .limit(1);

        return {
          hasAcknowledged: !!existing,
          version: CURRENT_DISCLAIMER_VERSION,
        };
      } catch (error) {
        console.warn('[Disclaimer] checkDisclaimerStatus failed, defaulting to unacknowledged:', error);
        return { hasAcknowledged: false, version: CURRENT_DISCLAIMER_VERSION };
      }
    }),

  /**
   * Analyze a drawing — the main two-stage pipeline (PD2.0 §4.1)
   *
   * Stage 1: extractDrawingData() — LLM extracts structured data ONLY
   * Stage 2: evaluateCompliance() — deterministic engine evaluates rules ONLY
   *
   * All results persisted to DB with full audit trail.
   */
  analyze: protectedProcedure
    .input(z.object({
      projectId: z.number().int().positive(),
      imageBase64: z.string().min(1),
      mimeType: z.enum(["image/jpeg", "image/png", "image/webp", "image/gif", "application/pdf"]),
      fileName: z.string().min(1).max(255),
      analysisType: z.enum(["structural", "fire-safety", "connections", "comprehensive"]),
      analysisQuality: z.enum(["fast", "standard", "detailed"]).default("standard"),
      drawingType: z.enum([
        'residential_multi_unit',
        'residential_single_family',
        'commercial_office',
        'institutional',
        'industrial',
        'mixed_use',
        'site_plan',
        'auto',
      ]).default('auto').optional(),
      // PD2.0 §6.3: Disclaimer must be acknowledged before analysis
      disclaimerAcknowledged: z.literal(true, {
        error: "You must acknowledge the disclaimer before proceeding.",
      }),
      disclaimerVersion: z.string(),
      cropRegion: z.object({
        x: z.number().int().nonnegative(),
        y: z.number().int().nonnegative(),
        width: z.number().int().positive(),
        height: z.number().int().positive(),
      }).optional(),
      municipality: z.string().max(100).optional(),
      drawingSetContext: z.object({
        projectName:           z.string().nullable().optional(),
        projectAddress:        z.string().nullable().optional(),
        architectFirm:         z.string().nullable().optional(),
        clientName:            z.string().nullable().optional(),
        buildingOccupancy:     z.string().nullable().optional(),
        numberOfStoreys:       z.number().nullable().optional(),
        basementPresent:       z.boolean().nullable().optional(),
        constructionType:      z.string().nullable().optional(),
        sprinklered:           z.boolean().nullable().optional(),
        codeEdition:           z.string().nullable().optional(),
        municipality:          z.string().nullable().optional(),
        province:              z.string().nullable().optional(),
        pageInventory:         z.array(z.object({ pageNum: z.number(), title: z.string(), type: z.string() })).optional(),
        floorHierarchy:        z.array(z.object({ floor: z.string(), pageNum: z.number() })).optional(),
        confirmedScale:        z.string().nullable().optional(),
        typicalCeilingHeightM: z.number().nullable().optional(),
        abbreviations:         z.record(z.string(), z.string()).optional(),
        exitLocations:         z.array(z.object({ description: z.string(), pageNum: z.number(), direction: z.string() })).optional(),
        stairLocations:        z.array(z.object({ pageNum: z.number(), location: z.string() })).optional(),
        currentRevision:       z.string().nullable().optional(),
        revisionDate:          z.string().nullable().optional(),
      }).optional(),
    }))
    .mutation(async ({ input, ctx }) => {
      // PD2.0 §6.3: Enforce disclaimer at API layer
      if (!input.disclaimerVersion) {
        throw new TRPCError({
          code: "FORBIDDEN",
          message: "Disclaimer not acknowledged",
        });
      }
      if (input.disclaimerVersion !== CURRENT_DISCLAIMER_VERSION) {
        throw new TRPCError({
          code: "FORBIDDEN",
          message: `Disclaimer version mismatch. Please re-acknowledge the current disclaimer (v${CURRENT_DISCLAIMER_VERSION}).`,
        });
      }

      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      // Validate attribution before storage uploads or any database writes.
      const [selectedProject] = await db.select({ id: projects.id })
        .from(projects)
        .where(and(eq(projects.id, input.projectId), eq(projects.userId, ctx.user.id)))
        .limit(1);
      if (!selectedProject) {
        throw new TRPCError({
          code: "FORBIDDEN",
          message: "Select a project you own before running analysis.",
        });
      }

      const ipAddress = extractIpAddress(ctx.req);
      const userAgent = ctx.req.headers["user-agent"] ?? "unknown";
      const sessionId = ctx.req.headers["x-session-id"] as string | undefined;

      // PD2.0 §4.2: Compute SHA-256 hash of the image at upload time (immutable)
      const imageBuffer = Buffer.from(input.imageBase64, "base64");
      const drawingHash = crypto.createHash("sha256").update(imageBuffer).digest("hex");

      // Upload drawing snapshot to S3 for immutable storage
      let drawingUrl = "";
      let drawingSnapshotKey: string | null = null;
      try {
        const ext = input.mimeType.split("/")[1];
        const key = `drawing-analyses/${ctx.user.id}/${drawingHash}.${ext}`;
        const uploaded = await storagePut(key, imageBuffer, input.mimeType);
        drawingUrl = uploaded.url;
        drawingSnapshotKey = key;
      } catch (err) {
        console.error("[DrawingAnalysis] S3 upload failed:", err);
        // Continue without S3 — analysis can still proceed
        drawingUrl = `data:${input.mimeType};base64,${input.imageBase64.substring(0, 50)}...`;
      }

      // Create the analysis record in DRAFT status
      const insertResult = await db.insert(drawingAnalyses).values({
        projectId: input.projectId,
        userId: ctx.user.id,
        drawingUrl,
        drawingHash,
        drawingSnapshotKey,
        drawingSnapshotMimeType: input.mimeType,
        drawingSnapshotSize: imageBuffer.length,
        analysisType: input.analysisType,
        analysisStatus: "DRAFT",
        disclaimerAcknowledged: true,
        disclaimerAcknowledgedAt: new Date(),
        disclaimerVersion: CURRENT_DISCLAIMER_VERSION,
        ruleEngineVersion: RULE_ENGINE_VERSION,
      });

      const analysisId = insertResult[0].insertId;

      // PD2.0 §7.2: DRAWING_UPLOADED audit event
      await insertAuditEvent({
        analysisId,
        userId: ctx.user.id,
        action: "DRAWING_UPLOADED",
        details: {
          fileName: input.fileName,
          mimeType: input.mimeType,
          fileSize: imageBuffer.length,
          drawingHash,
          analysisType: input.analysisType,
          disclaimerVersion: CURRENT_DISCLAIMER_VERSION,
        },
        userEmail: ctx.user.email,
        userFullName: ctx.user.name ?? null,
        ipAddress,
        userAgent,
        sessionId,
      });

      // PD2.0 §7.2: ANALYSIS_INITIATED audit event
      await insertAuditEvent({
        analysisId,
        userId: ctx.user.id,
        action: "ANALYSIS_INITIATED",
        details: { analysisType: input.analysisType, promptVersion: EXTRACTION_PROMPT_VERSION },
        userEmail: ctx.user.email,
        userFullName: ctx.user.name ?? null,
        ipAddress,
        userAgent,
        sessionId,
      });

      // ======================================================================
      // PDF PRE-PROCESSING (MULTI_PAGE_ENABLED guard)
      // Rasterizes pages, uploads to storage, records drawingPages rows.
      // When flag is off, PDF uploads are rejected early — Claude Vision
      // cannot process raw PDF bytes, so there is no fallback single-image path.
      // ======================================================================

      let page1Base64 = input.imageBase64;
      let page1MimeType: string = input.mimeType;
      let pageCount = 1;
      // Holds the preprocessed result so room detection can use it later
      let pdfPreprocessed: Awaited<ReturnType<typeof preprocessDocument>> | null = null;

      if (input.mimeType === "application/pdf") {
        if (!MULTI_PAGE_ENABLED) {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message: "Multi-page PDF analysis is not yet enabled. Please upload a JPEG, PNG, or WebP image.",
          });
        }
        try {
          pdfPreprocessed = await preprocessDocument(analysisId, ctx.user.id, imageBuffer);
          pageCount = pdfPreprocessed.pageCount;
          if (pdfPreprocessed.pages.length > 0) {
            page1Base64 = pdfPreprocessed.pages[0].base64;
            page1MimeType = pdfPreprocessed.pages[0].mimeType;
          }
        } catch (err) {
          console.error("[DrawingAnalysis] PDF preprocessing failed:", err);
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "PDF preprocessing failed. Please ensure the file is a valid, non-encrypted PDF.",
          });
        }
      }

      // ======================================================================
      // STAGE 1: LLM Extraction (PD2.0 §4.1 — extractor ONLY)
      // ======================================================================

      // Fetch project context to enrich the extraction prompt
      let projectContext: { occupancyCode?: string; province?: string; buildingType?: string; drawingType?: DrawingType } | undefined;
      try {
        const [proj] = await db
          .select({ occupancyCode: projects.occupancyCode, province: projects.province, buildingType: projects.buildingType })
          .from(projects)
          .where(eq(projects.id, input.projectId))
          .limit(1);
        if (proj) {
          projectContext = {
            occupancyCode: proj.occupancyCode ?? undefined,
            province: proj.province ?? undefined,
            buildingType: proj.buildingType ?? undefined,
            drawingType: input.drawingType === 'site_plan'
              ? 'auto'
              : (input.drawingType ?? 'auto') as DrawingType,
          };
        }
      } catch {
        // Non-critical — proceed without context
      }

      // Site plans have a dedicated extraction contract and do not enter the
      // floor-plan compliance pipeline. A pre-pass classified as floor_plan
      // falls through to the existing extraction path below.
      let classifiedPageType: 'site_plan' | 'floor_plan' | null = null;
      if (input.drawingType === 'site_plan') {
        const classificationPrompt = 'Is this a site plan showing property lines and building footprint from above, or a floor plan showing interior room layout? Answer with exactly one word: site_plan or floor_plan';
        const classification = await queuePageAnalysis(() => callAnthropicVision({
          imageBase64: page1Base64,
          mimeType: page1MimeType,
          systemPrompt: classificationPrompt,
          userPrompt: classificationPrompt,
          jsonSchema: {
            type: 'object',
            properties: { pageType: { type: 'string', enum: ['site_plan', 'floor_plan'] } },
            required: ['pageType'],
          },
          maxTokens: 32,
        }));

        classifiedPageType = (classification.parsed as { pageType?: string } | null)?.pageType === 'site_plan'
          ? 'site_plan'
          : 'floor_plan';

        let classifiedPageId: number | null = null;
        if (input.mimeType === 'application/pdf') {
          const [page] = await db
            .select({ id: drawingPages.id })
            .from(drawingPages)
            .where(and(eq(drawingPages.drawingId, analysisId), eq(drawingPages.pageNumber, 1)))
            .limit(1);
          classifiedPageId = page?.id ?? null;
          if (classifiedPageId !== null) {
            await db.update(drawingPages)
              .set({ pageType: classifiedPageType })
              .where(eq(drawingPages.id, classifiedPageId));
          }
        } else if (classifiedPageType === 'site_plan') {
          const pageInsert = await db.insert(drawingPages).values({
            drawingId: analysisId,
            pageNumber: 1,
            widthPx: 0,
            heightPx: 0,
            pageType: classifiedPageType,
            preprocessedUrl: drawingUrl || null,
            cropRegionJson: input.cropRegion ?? null,
            cropRegionSetAt: input.cropRegion ? new Date() : null,
          });
          classifiedPageId = pageInsert[0].insertId;
        }

        if (classifiedPageType === 'site_plan') {
          if (classifiedPageId === null) {
            throw new TRPCError({
              code: 'INTERNAL_SERVER_ERROR',
              message: 'Site plan page record was not created',
            });
          }

          const prompts = buildSitePlanPrompts();
          const sitePlanResponse = await queuePageAnalysis(() => callAnthropicVision({
            imageBase64: page1Base64,
            mimeType: page1MimeType,
            systemPrompt: prompts.system,
            userPrompt: prompts.user,
            jsonSchema: {
              type: 'object',
              properties: {
                parcelAreaM2: { type: ['number', 'null'] },
                parcelWidthM: { type: ['number', 'null'] },
                parcelDepthM: { type: ['number', 'null'] },
                frontSetbackM: { type: ['number', 'null'] },
                rearSetbackM: { type: ['number', 'null'] },
                sideSetbackLeftM: { type: ['number', 'null'] },
                sideSetbackRightM: { type: ['number', 'null'] },
                buildingFootprintM2: { type: ['number', 'null'] },
                lotCoveragePct: { type: ['number', 'null'] },
                mainFloorGeodeticM: { type: ['number', 'null'] },
                roofPeakGeodeticM: { type: ['number', 'null'] },
                footingGeodeticM: { type: ['number', 'null'] },
                hasLane: { type: ['boolean', 'null'] },
                parkingStalls: { type: ['number', 'null'] },
                parkingSurfaceType: { type: ['string', 'null'] },
                northArrowDetected: { type: ['boolean', 'null'] },
                municipalAddress: { type: ['string', 'null'] },
                detectedScale: { type: ['string', 'null'] },
                scaleConfidence: { type: ['number', 'null'] },
              },
              required: [
                'parcelAreaM2', 'parcelWidthM', 'parcelDepthM', 'frontSetbackM',
                'rearSetbackM', 'sideSetbackLeftM', 'sideSetbackRightM',
                'buildingFootprintM2', 'lotCoveragePct', 'mainFloorGeodeticM',
                'roofPeakGeodeticM', 'footingGeodeticM', 'hasLane', 'parkingStalls',
                'parkingSurfaceType', 'northArrowDetected', 'municipalAddress',
                'detectedScale', 'scaleConfidence',
              ],
            },
          }));

          const parsedSitePlan = SitePlanExtractionSchema.safeParse(sitePlanResponse.parsed);
          const sitePlan = parsedSitePlan.success
            ? {
                ...parsedSitePlan.data,
                lotCoveragePct: deriveLotCoveragePct(
                  parsedSitePlan.data.buildingFootprintM2,
                  parsedSitePlan.data.parcelAreaM2,
                ),
              }
            : null;
          const decimalValue = (value: number | null | undefined) => value == null ? null : String(value);

          await db.insert(sitePlanExtractions).values({
            pageId: classifiedPageId,
            drawingId: analysisId,
            parcelAreaM2: decimalValue(sitePlan?.parcelAreaM2),
            parcelWidthM: decimalValue(sitePlan?.parcelWidthM),
            parcelDepthM: decimalValue(sitePlan?.parcelDepthM),
            frontSetbackM: decimalValue(sitePlan?.frontSetbackM),
            rearSetbackM: decimalValue(sitePlan?.rearSetbackM),
            sideSetbackLeftM: decimalValue(sitePlan?.sideSetbackLeftM),
            sideSetbackRightM: decimalValue(sitePlan?.sideSetbackRightM),
            buildingFootprintM2: decimalValue(sitePlan?.buildingFootprintM2),
            lotCoveragePct: decimalValue(sitePlan?.lotCoveragePct),
            mainFloorGeodeticM: decimalValue(sitePlan?.mainFloorGeodeticM),
            roofPeakGeodeticM: decimalValue(sitePlan?.roofPeakGeodeticM),
            footingGeodeticM: decimalValue(sitePlan?.footingGeodeticM),
            hasLane: sitePlan?.hasLane == null ? null : sitePlan.hasLane ? 1 : 0,
            parkingStalls: sitePlan?.parkingStalls ?? null,
            parkingSurfaceType: sitePlan?.parkingSurfaceType ?? null,
            northArrowDetected: sitePlan?.northArrowDetected == null ? null : sitePlan.northArrowDetected ? 1 : 0,
            municipalAddress: sitePlan?.municipalAddress ?? null,
            detectedScale: sitePlan?.detectedScale ?? null,
            scaleConfidence: decimalValue(sitePlan?.scaleConfidence),
            extractionModel: sitePlanResponse.modelVersion,
            extractionPromptVersion: EXTRACTION_PROMPT_VERSION,
            extractionConfidence: decimalValue(sitePlan?.scaleConfidence),
            rawExtractionJson: sitePlanResponse.rawText,
          });

          await db.update(drawingAnalyses).set({
            analysisStatus: 'UNDER_REVIEW',
            llmModelVersion: sitePlanResponse.modelVersion,
            updatedAt: new Date(),
          }).where(eq(drawingAnalyses.id, analysisId));

          await insertAuditEvent({
            analysisId,
            userId: ctx.user.id,
            action: 'EXTRACTION_COMPLETED',
            details: {
              modelVersion: sitePlanResponse.modelVersion,
              promptVersion: EXTRACTION_PROMPT_VERSION,
              drawingType: classifiedPageType,
              parsed: parsedSitePlan.success,
            },
            userEmail: ctx.user.email,
            userFullName: ctx.user.name ?? null,
            ipAddress,
            userAgent,
            sessionId,
          });

          return {
            analysisId,
            analysisStatus: 'UNDER_REVIEW' as const,
            disclaimerAcknowledged: true,
            disclaimerVersion: CURRENT_DISCLAIMER_VERSION,
            llmModelVersion: sitePlanResponse.modelVersion,
            ruleEngineVersion: RULE_ENGINE_VERSION,
            pageCount,
            complianceScore: null,
            complianceLevel: null,
            ruleEvaluations: [],
            issues: parsedSitePlan.success ? [] : [{
              severity: 'major',
              clause: 'site-plan-extraction',
              description: 'Site plan response could not be validated',
              details: parsedSitePlan.error.message,
            }],
            recommendations: [],
            extractedData: {
              drawingType: classifiedPageType,
              sitePlan,
            },
          };
        }
      }

      let extractionResult;
      let modelVersion = "unknown";
      try {
        const extracted = await queuePageAnalysis(() => extractDrawingData(
          page1Base64,
          page1MimeType,
          input.analysisType,
          input.analysisQuality,
          projectContext,
        ));
        extractionResult = extracted.data;
        modelVersion = extracted.modelVersion;

        // Persist extraction result (PD2.0 §4.1: LLM output stored separately)
        await db.insert(drawingDataExtractions).values({
          analysisId,
          extractedData: JSON.stringify(extractionResult),
          extractionModel: modelVersion,
          extractionPromptVersion: EXTRACTION_PROMPT_VERSION,
          extractionConfidence: String(
            extractionResult.structural?.confidence ??
            extractionResult.fireSafety?.confidence ??
            extractionResult.connections?.confidence ??
            0.5
          ) as any,
          extractedAt: new Date(),
        });

        // PD2.0 §7.2: EXTRACTION_COMPLETED audit event
        await insertAuditEvent({
          analysisId,
          userId: ctx.user.id,
          action: "EXTRACTION_COMPLETED",
          details: {
            modelVersion,
            promptVersion: EXTRACTION_PROMPT_VERSION,
            drawingType: extractionResult.drawingType,
            structuralMembersFound: extractionResult.structural?.memberSizes?.length ?? 0,
            fireSafetyExitsFound: extractionResult.fireSafety?.exitWidths?.length ?? 0,
            connectionsFound: extractionResult.connections?.fastenerTypes?.length ?? 0,
          },
          userEmail: ctx.user.email,
          userFullName: ctx.user.name ?? null,
          ipAddress,
          userAgent,
          sessionId,
        });
      } catch (err) {
        console.error("[DrawingAnalysis] Stage 1 extraction failed:", err);
        // Update analysis to reflect failure
        await db.update(drawingAnalyses)
          .set({ analysisStatus: "REJECTED", llmModelVersion: "error" })
          .where(eq(drawingAnalyses.id, analysisId));
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Drawing extraction failed. If this page is a 3D rendering, elevation, or detail sheet, please select a floor plan page instead. Otherwise try uploading a higher-resolution scan.",
        });
      }

      // ======================================================================
      // STAGE 2: Deterministic Compliance Evaluation (PD2.0 §4.1 — judge ONLY)
      // ======================================================================
      const engineOutput = evaluateCompliance(extractionResult);

      // Persist each rule evaluation result
      for (const ruleEval of engineOutput.ruleEvaluations) {
        await db.insert(complianceEvaluationResults).values({
          analysisId,
          ruleId: 0, // No FK to nbcRules table yet — use 0 as placeholder
          ruleVersion: 1,
          evaluationResult: ruleEval.result,
          evaluationDetails: JSON.stringify({
            ruleId: ruleEval.ruleId,
            clause: ruleEval.clause,
            description: ruleEval.description,
            category: ruleEval.category,
            severity: ruleEval.severity,
            details: ruleEval.details,
          }),
          evaluatedAt: new Date(),
        });
      }

      // PD2.0 §7.2: EVALUATION_COMPLETED audit event
      await insertAuditEvent({
        analysisId,
        userId: ctx.user.id,
        action: "EVALUATION_COMPLETED",
        details: {
          ruleEngineVersion: RULE_ENGINE_VERSION,
          rulesEvaluated: engineOutput.ruleEvaluations.length,
          passCount: engineOutput.ruleEvaluations.filter(r => r.result === "PASS").length,
          failCount: engineOutput.ruleEvaluations.filter(r => r.result === "FAIL").length,
          conditionalCount: engineOutput.ruleEvaluations.filter(r => r.result === "CONDITIONAL").length,
          unableCount: engineOutput.ruleEvaluations.filter(r => r.result === "UNABLE_TO_EVALUATE").length,
        },
        userEmail: ctx.user.email,
        userFullName: ctx.user.name ?? null,
        ipAddress,
        userAgent,
        sessionId,
      });

      // PD2.0 §7.2: SCORE_CALCULATED audit event
      await insertAuditEvent({
        analysisId,
        userId: ctx.user.id,
        action: "SCORE_CALCULATED",
        details: {
          complianceScore: engineOutput.complianceScore,
          complianceLevel: engineOutput.complianceLevel,
          issueCount: engineOutput.issues.length,
          recommendationCount: engineOutput.recommendations.length,
        },
        userEmail: ctx.user.email,
        userFullName: ctx.user.name ?? null,
        ipAddress,
        userAgent,
        sessionId,
      });

      // Update the analysis record with results — status moves to UNDER_REVIEW (PD2.0 §4.3)
      try {
        await db.update(drawingAnalyses).set({
          analysisStatus: "UNDER_REVIEW",
          complianceScore: engineOutput.complianceScore,
          complianceLevel: engineOutput.complianceLevel,
          structuralStatus: JSON.stringify(extractionResult.structural ?? {}),
          fireSafetyStatus: JSON.stringify(extractionResult.fireSafety ?? {}),
          connectionStatus: JSON.stringify(extractionResult.connections ?? {}),
          issues: JSON.stringify(engineOutput.issues),
          recommendations: JSON.stringify(engineOutput.recommendations),
          llmModelVersion: modelVersion,
          ruleEngineVersion: RULE_ENGINE_VERSION,
          updatedAt: new Date(),
        }).where(eq(drawingAnalyses.id, analysisId));
      } catch (updateError) {
        console.error('[DrawingAnalysis] UPDATE failed (non-fatal):', JSON.stringify({
          message: (updateError as any)?.message,
          code: (updateError as any)?.code,
          sqlMessage: (updateError as any)?.cause?.sqlMessage,
          sql: (updateError as any)?.cause?.sql?.substring(0, 200),
        }));
        // Continue — don't throw, results still returned to client
      }

      // ======================================================================
      // ROOM DETECTION — non-blocking, runs after main analysis completes
      // ======================================================================

      // Fetch calling user's orgId for org-aware training example injection
      const [callerRow] = await db
        .select({ orgId: users.orgId })
        .from(users)
        .where(eq(users.id, ctx.user.id))
        .limit(1);
      const callerOrgId = callerRow?.orgId ?? null;

      // PDF path: room detection from rasterized page 1
      if (pdfPreprocessed && pdfPreprocessed.pages.length > 0) {
        const page1b64 = pdfPreprocessed.pages[0].base64;
        const page1Dims = pdfPreprocessed.pages[0];
        const clientCropRegion = input.cropRegion;
        // Look up the drawingPages row inserted during preprocessing
        db.select()
          .from(drawingPages)
          .where(and(eq(drawingPages.drawingId, analysisId), eq(drawingPages.pageNumber, 1)))
          .limit(1)
          .then(([page1Record]) => {
            if (!page1Record) return;
            // Prefer client-side crop region; fall back to page's persisted region
            const pageCrop = page1Record.cropRegionJson
              ? (typeof page1Record.cropRegionJson === 'string'
                  ? safeJsonParse(page1Record.cropRegionJson)
                  : page1Record.cropRegionJson) as { x: number; y: number; width: number; height: number } | null
              : null;
            const activeCrop = clientCropRegion ?? pageCrop ?? undefined;
            console.log('[RoomDetection] Queuing room detection for page', page1Record.id, activeCrop ? '(with crop region)' : '');

            // Non-blocking wall extraction — PDF path
            wallEngineQueue.add(async () => {
              await runWallEngine(
                input.imageBase64,
                1,
                page1Record.id,
                analysisId,
                page1Dims.widthPx,
                page1Dims.heightPx,
                activeCrop ?? null,
              );
            }).catch(err => console.error('[WallEngine] Queue error:', err));

            return queuePageAnalysis(() =>
              detectRoomsFromPage(page1b64, page1Record.id, input.projectId, 1, projectContext, 'AB', activeCrop ?? undefined, callerOrgId, input.drawingSetContext as any ?? null)
            );
          })
          .catch(err => console.error('[RoomDetection] PDF page 1 detection failed:', err));
      }

      // Single-image path: create a synthetic drawingPage row, then detect
      if (input.mimeType !== "application/pdf") {
        const clientCropRegion = input.cropRegion;
        db.insert(drawingPages).values({
          drawingId: analysisId,
          pageNumber: 1,
          widthPx: 0,
          heightPx: 0,
          pageType: classifiedPageType,
          preprocessedUrl: drawingUrl || null,
          cropRegionJson: clientCropRegion ?? null,
          cropRegionSetAt: clientCropRegion ? new Date() : null,
        })
          .then(result => {
            const syntheticPageId = result[0].insertId;
            console.log('[RoomDetection] Queuing room detection for page', syntheticPageId, clientCropRegion ? '(with crop region)' : '');
            return queuePageAnalysis(() =>
              detectRoomsFromPage(input.imageBase64, syntheticPageId, input.projectId, 1, projectContext, 'AB', clientCropRegion ?? undefined, callerOrgId, input.drawingSetContext as any ?? null)
            );
          })
          .catch(err => console.error('[RoomDetection] Image detection failed:', err));
      }

      // PD2.0 §6.4: Response payload must include all required fields
      return {
        analysisId,
        analysisStatus: "UNDER_REVIEW" as const,
        disclaimerAcknowledged: true,
        disclaimerVersion: CURRENT_DISCLAIMER_VERSION,
        llmModelVersion: modelVersion,
        ruleEngineVersion: RULE_ENGINE_VERSION,
        pageCount,
        complianceScore: engineOutput.complianceScore,
        complianceLevel: engineOutput.complianceLevel,
        ruleEvaluations: engineOutput.ruleEvaluations,
        issues: engineOutput.issues,
        recommendations: engineOutput.recommendations,
        extractedData: {
          drawingType: extractionResult.drawingType,
          jurisdiction: extractionResult.jurisdiction,
          structural: extractionResult.structural,
          fireSafety: extractionResult.fireSafety,
          connections: extractionResult.connections,
        },
      };
    }),

  /**
   * Get analysis by ID (PD2.0 §7.2: ANALYSIS_VIEWED audit event)
   */
  getAnalysis: protectedProcedure
    .input(z.object({ analysisId: z.number().int().positive() }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const [analysis] = await db
        .select()
        .from(drawingAnalyses)
        .where(and(
          eq(drawingAnalyses.id, input.analysisId),
          eq(drawingAnalyses.userId, ctx.user.id)
        ));

      if (!analysis) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Analysis not found" });
      }

      // PD2.0 §7.2: ANALYSIS_VIEWED audit event (INSERT-ONLY)
      await insertAuditEvent({
        analysisId: input.analysisId,
        userId: ctx.user.id,
        action: "ANALYSIS_VIEWED",
        details: { analysisStatus: analysis.analysisStatus },
        userEmail: ctx.user.email,
        userFullName: ctx.user.name ?? null,
        ipAddress: extractIpAddress(ctx.req),
        userAgent: ctx.req.headers["user-agent"] ?? "unknown",
      });

      return {
        ...analysis,
        // PD2.0 §6.4: Always include required fields
        disclaimerAcknowledged: analysis.disclaimerAcknowledged,
        disclaimerVersion: analysis.disclaimerVersion,
        llmModelVersion: analysis.llmModelVersion,
        ruleEngineVersion: analysis.ruleEngineVersion,
        analysisStatus: analysis.analysisStatus,
      };
    }),

  /**
   * List analyses for a project
   */
  listByProject: protectedProcedure
    .input(z.object({ projectId: z.number().int().positive() }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const analyses = await db
        .select()
        .from(drawingAnalyses)
        .where(and(
          eq(drawingAnalyses.projectId, input.projectId),
          eq(drawingAnalyses.userId, ctx.user.id)
        ))
        .orderBy(desc(drawingAnalyses.createdAt))
        .limit(20);

      return analyses;
    }),

  /**
   * Get audit trail for an analysis (read-only view)
   */
  getAuditTrail: protectedProcedure
    .input(z.object({ analysisId: z.number().int().positive() }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      // Verify ownership
      const [analysis] = await db
        .select({ id: drawingAnalyses.id })
        .from(drawingAnalyses)
        .where(and(
          eq(drawingAnalyses.id, input.analysisId),
          eq(drawingAnalyses.userId, ctx.user.id)
        ));

      if (!analysis) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Analysis not found" });
      }

      const trail = await db
        .select()
        .from(complianceAuditTrail)
        .where(eq(complianceAuditTrail.analysisId, input.analysisId))
        .orderBy(desc(complianceAuditTrail.timestamp))
        .limit(200);

      return trail;
    }),

  /**
   * Professional validation — transitions UNDER_REVIEW → VALID (PD2.0 §4.3)
   * Only accessible to authenticated users with professional credentials
   */
  validateAnalysis: protectedProcedure
    .input(z.object({
      analysisId: z.number().int().positive(),
      licenseNumber: z.string().min(1).max(100),
      professionalAssociation: z.string().min(1).max(100),
      jurisdiction: z.string().min(1).max(100),
      validationNotes: z.string().max(2000).optional(),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const [analysis] = await db
        .select()
        .from(drawingAnalyses)
        .where(and(
          eq(drawingAnalyses.id, input.analysisId),
          eq(drawingAnalyses.userId, ctx.user.id)
        ));

      if (!analysis) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Analysis not found" });
      }

      // PD2.0 §4.3: Only UNDER_REVIEW analyses can be validated
      if (analysis.analysisStatus !== "UNDER_REVIEW") {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: `Cannot validate analysis in status '${analysis.analysisStatus}'. Only UNDER_REVIEW analyses can be validated.`,
        });
      }

      // Transition to VALID
      await db.update(drawingAnalyses).set({
        analysisStatus: "VALID",
        validatedAt: new Date(),
        validatedByUserId: ctx.user.id,
        validatedByLicenseNumber: input.licenseNumber,
        validatedByAssociation: input.professionalAssociation,
        updatedAt: new Date(),
      }).where(eq(drawingAnalyses.id, input.analysisId));

      // PD2.0 §7.2: PROFESSIONAL_ACCEPTED + SIGNATURE_APPLIED (single transaction)
      await insertAuditEvent({
        analysisId: input.analysisId,
        userId: ctx.user.id,
        action: "PROFESSIONAL_ACCEPTED",
        details: {
          licenseNumber: input.licenseNumber,
          association: input.professionalAssociation,
          jurisdiction: input.jurisdiction,
          notes: input.validationNotes ?? null,
          validatedAt: new Date().toISOString(),
        },
        userEmail: ctx.user.email,
        userFullName: ctx.user.name ?? null,
        professionalLicenseNumber: input.licenseNumber,
        professionalAssociation: input.professionalAssociation,
        jurisdiction: input.jurisdiction,
        ipAddress: extractIpAddress(ctx.req),
        userAgent: ctx.req.headers["user-agent"] ?? "unknown",
      });

      return { success: true, analysisStatus: "VALID" as const };
    }),

  /**
   * Export compliance report as structured JSON for PDF generation (PD2.0 §9.1)
   * Only available for VALID-status analyses.
   * The client uses this data to generate a PDF report.
   */
  exportReport: protectedProcedure
    .input(z.object({
      analysisId: z.number().int().positive(),
    }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const [analysis] = await db
        .select()
        .from(drawingAnalyses)
        .where(and(
          eq(drawingAnalyses.id, input.analysisId),
          eq(drawingAnalyses.userId, ctx.user.id)
        ));

      if (!analysis) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Analysis not found" });
      }

      // PD2.0 §9.1: Only VALID analyses can be exported
      if (analysis.analysisStatus !== "VALID") {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: `Only VALID analyses can be exported. Current status: ${analysis.analysisStatus}`,
        });
      }

      // Fetch audit trail for the report
      const auditTrail = await db
        .select()
        .from(complianceAuditTrail)
        .where(eq(complianceAuditTrail.analysisId, input.analysisId))
        .orderBy(desc(complianceAuditTrail.timestamp))
        .limit(200);

      // PD2.0 §7.2: REPORT_EXPORTED audit event
      await insertAuditEvent({
        analysisId: input.analysisId,
        userId: ctx.user.id,
        action: "REPORT_EXPORTED",
        details: { exportFormat: "pdf", exportedAt: new Date().toISOString() },
        userEmail: ctx.user.email,
        userFullName: ctx.user.name ?? null,
        ipAddress: extractIpAddress(ctx.req),
        userAgent: ctx.req.headers["user-agent"] ?? "unknown",
      });

      // Find the PROFESSIONAL_ACCEPTED event for reviewer info
      const professionalEvent = auditTrail.find(e => e.action === "PROFESSIONAL_ACCEPTED");

      return {
        analysisId: analysis.id,
        analysisStatus: analysis.analysisStatus,
        analysisType: analysis.analysisType,
        complianceScore: analysis.complianceScore,
        complianceLevel: analysis.complianceLevel,
        issues: analysis.issues ? JSON.parse(analysis.issues as string) : [],
        recommendations: analysis.recommendations ? JSON.parse(analysis.recommendations as string) : [],
        llmModelVersion: analysis.llmModelVersion,
        ruleEngineVersion: analysis.ruleEngineVersion,
        disclaimerVersion: analysis.disclaimerVersion,
        createdAt: analysis.createdAt,
        validatedAt: analysis.validatedAt,
        validatedByLicenseNumber: analysis.validatedByLicenseNumber,
        validatedByAssociation: analysis.validatedByAssociation,
        reviewerName: ctx.user.name,
        reviewerEmail: ctx.user.email,
        // Audit trail summary
        auditTrailSummary: auditTrail.map(e => ({
          action: e.action,
          timestamp: e.timestamp,
          userEmail: e.userEmail,
          details: typeof e.details === "string" ? JSON.parse(e.details) : e.details,
        })),
        // Professional event details
        professionalDetails: professionalEvent ? {
          licenseNumber: professionalEvent.professionalLicenseNumber,
          association: professionalEvent.professionalAssociation,
          jurisdiction: professionalEvent.jurisdiction,
          notes: (typeof professionalEvent.details === "string"
            ? JSON.parse(professionalEvent.details)
            : professionalEvent.details)?.notes ?? null,
        } : null,
      };
    }),

  /**
   * Reject analysis — transitions UNDER_REVIEW → REJECTED (PD2.0 §4.3)
   */
  rejectAnalysis: protectedProcedure
    .input(z.object({
      analysisId: z.number().int().positive(),
      rejectionReason: z.string().min(1).max(2000),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const [analysis] = await db
        .select()
        .from(drawingAnalyses)
        .where(and(
          eq(drawingAnalyses.id, input.analysisId),
          eq(drawingAnalyses.userId, ctx.user.id)
        ));

      if (!analysis) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Analysis not found" });
      }

      if (analysis.analysisStatus !== "UNDER_REVIEW") {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: `Cannot reject analysis in status '${analysis.analysisStatus}'.`,
        });
      }

      await db.update(drawingAnalyses).set({
        analysisStatus: "REJECTED",
        updatedAt: new Date(),
      }).where(eq(drawingAnalyses.id, input.analysisId));

      // PD2.0 §7.2: PROFESSIONAL_REJECTED audit event
      await insertAuditEvent({
        analysisId: input.analysisId,
        userId: ctx.user.id,
        action: "PROFESSIONAL_REJECTED",
        details: { rejectionReason: input.rejectionReason },
        userEmail: ctx.user.email,
        userFullName: ctx.user.name ?? null,
        ipAddress: extractIpAddress(ctx.req),
        userAgent: ctx.req.headers["user-agent"] ?? "unknown",
      });

      return { success: true, analysisStatus: "REJECTED" as const };
    }),

  /**
   * Get all detected rooms and features for a drawing (all pages)
   */
  getRoomsForDrawing: protectedProcedure
    .input(z.object({ drawingId: z.number().int().positive() }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      // Verify ownership
      const [analysis] = await db
        .select({ id: drawingAnalyses.id })
        .from(drawingAnalyses)
        .where(and(eq(drawingAnalyses.id, input.drawingId), eq(drawingAnalyses.userId, ctx.user.id)));

      if (!analysis) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Drawing not found" });
      }

      const pages = await db
        .select()
        .from(drawingPages)
        .where(eq(drawingPages.drawingId, input.drawingId));

      const rooms = [];
      const pagesWithDoors = [];
      for (const page of pages) {
        const pageRooms = await db
          .select()
          .from(detectedRooms)
          .where(eq(detectedRooms.pageId, page.id));

        const doorFeatures = await db
          .select()
          .from(detectedFeatures)
          .where(and(
            eq(detectedFeatures.pageId, page.id),
            eq(detectedFeatures.featureType, 'door'),
          ));

        pagesWithDoors.push({
          ...page,
          doorFeatures: doorFeatures.map(f => ({
            ...f,
            geometryJson: typeof f.geometryJson === 'string'
              ? safeJsonParse(f.geometryJson)
              : f.geometryJson,
          })),
        });

        for (const room of pageRooms) {
          const features = await db
            .select()
            .from(detectedFeatures)
            .where(eq(detectedFeatures.roomId, room.id));

          const compliance = await db
            .select()
            .from(complianceResults)
            .where(eq(complianceResults.roomId, room.id));

          rooms.push({
            ...normalizeRoomFacts(room),
            boundingBox: safeJsonParse(room.boundingBoxJson),
            polygonJson: room.polygonJson ? (typeof room.polygonJson === 'string' ? safeJsonParse(room.polygonJson) : room.polygonJson) : null,
            flags: (safeJsonParse(room.flagsJson) as any[]) ?? [],
            features: features.map(f => ({
              ...f,
              position: safeJsonParse(f.positionJson),
              metadata: safeJsonParse(f.metadataJson),
            })),
            compliance,
          });
        }
      }

      console.log('[RoomQuery] returning', rooms.length, 'rooms for drawingId', input.drawingId);
      return { pages: pagesWithDoors, rooms };
    }),

  /**
   * Get per-room compliance results for a project
   */
  getRoomCompliance: protectedProcedure
    .input(z.object({
      drawingId: z.number(),
      projectId: z.number()
    }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: 'DB unavailable' });

      const pages = await db
        .select()
        .from(drawingPages)
        .where(eq(drawingPages.drawingId, input.drawingId));

      const rooms = [];
      for (const page of pages) {
        const pageRooms = await db
          .select()
          .from(detectedRooms)
          .where(eq(detectedRooms.pageId, page.id))
          .limit(100);
        rooms.push(...pageRooms.map(normalizeRoomFacts));
      }

      const results = [];
      for (const room of rooms) {
        const compliance = await db
          .select()
          .from(complianceResults)
          .where(eq(complianceResults.roomId, room.id));

        results.push({
          room: {
            ...room,
            boundingBox: safeJsonParse(room.boundingBoxJson),
          },
          compliance,
        });
      }

      return results;
    }),

  /**
   * Calculate travel distances for all detected rooms on a drawing (NBC 3.4.2.5).
   * pixelsPerMm is computed client-side from the calibration state and passed here.
   */
  getTravelDistances: protectedProcedure
    .input(z.object({
      drawingId: z.number().int().positive(),
      pixelsPerMm: z.number().nullable(),
    }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      // Verify ownership and get project for sprinklersRequired
      const [analysis] = await db
        .select({ id: drawingAnalyses.id, projectId: drawingAnalyses.projectId })
        .from(drawingAnalyses)
        .where(and(eq(drawingAnalyses.id, input.drawingId), eq(drawingAnalyses.userId, ctx.user.id)));

      if (!analysis) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Drawing not found" });
      }

      // Read sprinklersRequired from the linked project (0/null = false, 1 = true)
      let sprinklered = false;
      if (analysis.projectId) {
        const [project] = await db
          .select({ sprinklersRequired: projects.sprinklersRequired })
          .from(projects)
          .where(eq(projects.id, analysis.projectId));
        sprinklered = project?.sprinklersRequired === 1;
      }

      // Fetch all pages → rooms → features
      const pages = await db
        .select()
        .from(drawingPages)
        .where(eq(drawingPages.drawingId, input.drawingId));

      const roomInputs = [];
      for (const page of pages) {
        const pageRooms = await db
          .select()
          .from(detectedRooms)
          .where(eq(detectedRooms.pageId, page.id));

        for (const room of pageRooms) {
          const features = await db
            .select({ featureType: detectedFeatures.featureType })
            .from(detectedFeatures)
            .where(eq(detectedFeatures.roomId, room.id));

          roomInputs.push({
            id: room.id,
            roomLabel: room.roomLabel ?? '',
            boundingBox: safeJsonParse(room.boundingBoxJson) as { x: number; y: number; width: number; height: number } | null,
            occupancyGroup: normalizeRoomFacts(room).occupancyGroup ?? null,
            features,
          });
        }
      }

      const results = calculateTravelDistances(roomInputs, input.pixelsPerMm, sprinklered);
      return { results, sprinklered };
    }),

  saveCalibration: protectedProcedure
    .input(z.object({
      pageId: z.number().int().positive(),
      calibrationScale: z.number().positive(),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      // Verify the page belongs to a drawing owned by the current user
      const [page] = await db
        .select({ drawingId: drawingPages.drawingId })
        .from(drawingPages)
        .where(eq(drawingPages.id, input.pageId));

      if (!page) throw new TRPCError({ code: "NOT_FOUND", message: "Page not found" });

      const [analysis] = await db
        .select({ id: drawingAnalyses.id })
        .from(drawingAnalyses)
        .where(and(eq(drawingAnalyses.id, page.drawingId), eq(drawingAnalyses.userId, ctx.user.id)));

      if (!analysis) throw new TRPCError({ code: "FORBIDDEN", message: "Access denied" });

      await db
        .update(drawingPages)
        .set({ calibrationScale: parseFloat(input.calibrationScale.toFixed(6)) })
        .where(eq(drawingPages.id, input.pageId));

      return { ok: true };
    }),

  saveCropRegion: protectedProcedure
    .input(z.object({
      pageId: z.number().int().positive(),
      region: z.object({
        x: z.number().int().nonnegative(),
        y: z.number().int().nonnegative(),
        width: z.number().int().positive(),
        height: z.number().int().positive(),
      }),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const [page] = await db
        .select({ drawingId: drawingPages.drawingId })
        .from(drawingPages)
        .where(eq(drawingPages.id, input.pageId));

      if (!page) throw new TRPCError({ code: "NOT_FOUND", message: "Page not found" });

      const [analysis] = await db
        .select({ id: drawingAnalyses.id })
        .from(drawingAnalyses)
        .where(and(eq(drawingAnalyses.id, page.drawingId), eq(drawingAnalyses.userId, ctx.user.id)));

      if (!analysis) throw new TRPCError({ code: "FORBIDDEN", message: "Access denied" });

      const now = new Date();
      await db
        .update(drawingPages)
        .set({ cropRegionJson: input.region, cropRegionInheritedFrom: null, cropRegionSetAt: now })
        .where(eq(drawingPages.id, input.pageId));

      return { ok: true };
    }),

  clearCropRegion: protectedProcedure
    .input(z.object({ pageId: z.number().int().positive() }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const [page] = await db
        .select({ drawingId: drawingPages.drawingId })
        .from(drawingPages)
        .where(eq(drawingPages.id, input.pageId));

      if (!page) throw new TRPCError({ code: "NOT_FOUND", message: "Page not found" });

      const [analysis] = await db
        .select({ id: drawingAnalyses.id })
        .from(drawingAnalyses)
        .where(and(eq(drawingAnalyses.id, page.drawingId), eq(drawingAnalyses.userId, ctx.user.id)));

      if (!analysis) throw new TRPCError({ code: "FORBIDDEN", message: "Access denied" });

      await db
        .update(drawingPages)
        .set({ cropRegionJson: null, cropRegionInheritedFrom: null, cropRegionSetAt: null })
        .where(eq(drawingPages.id, input.pageId));

      return { ok: true };
    }),

  getCropRegion: protectedProcedure
    .input(z.object({ pageId: z.number().int().positive() }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });

      const [page] = await db
        .select()
        .from(drawingPages)
        .where(eq(drawingPages.id, input.pageId));

      if (!page) throw new TRPCError({ code: "NOT_FOUND", message: "Page not found" });

      const [analysis] = await db
        .select({ id: drawingAnalyses.id })
        .from(drawingAnalyses)
        .where(and(eq(drawingAnalyses.id, page.drawingId), eq(drawingAnalyses.userId, ctx.user.id)));

      if (!analysis) throw new TRPCError({ code: "FORBIDDEN", message: "Access denied" });

      if (page.cropRegionJson) {
        const region = typeof page.cropRegionJson === 'string'
          ? safeJsonParse(page.cropRegionJson)
          : page.cropRegionJson;
        return { region, inheritedFrom: page.cropRegionInheritedFrom };
      }

      return { region: null, inheritedFrom: null };
    }),

  /**
   * Phase C — save a DDA ray-cast polygon for a room.
   * Ownership: drawingPageId → drawingAnalyses.userId must equal ctx.user.id
   */
  saveRoomPolygon: protectedProcedure
    .input(z.object({
      drawingPageId: z.number().int().positive(),
      roomLabel: z.string().max(100),
      polygonPoints: z.array(z.object({ x: z.number(), y: z.number() })).max(720),
      areaM2: z.number().optional(),
      occupancyGroup: z.string().optional(),
      spaceType: z.enum([
        'room', 'corridor', 'stairwell', 'closet', 'storage',
        'mechanical', 'garage', 'exterior', 'vestibule', 'lobby', 'other',
      ]).optional(),
      seedX: z.number(),
      seedY: z.number(),
      doorBarriers: z.array(z.object({
        x1: z.number(), y1: z.number(),
        x2: z.number(), y2: z.number(),
      })).optional(),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: 'DB unavailable' });

      const [page] = await db
        .select({ drawingId: drawingPages.drawingId })
        .from(drawingPages)
        .where(eq(drawingPages.id, input.drawingPageId));
      if (!page) throw new TRPCError({ code: 'NOT_FOUND', message: 'Page not found' });

      const [analysisRow] = await db
        .select({ id: drawingAnalyses.id, projectId: drawingAnalyses.projectId })
        .from(drawingAnalyses)
        .where(and(eq(drawingAnalyses.id, page.drawingId), eq(drawingAnalyses.userId, ctx.user.id)));
      if (!analysisRow) throw new TRPCError({ code: 'FORBIDDEN', message: 'Access denied' });

      const projectId = analysisRow.projectId;
      if (projectId == null || !Number.isSafeInteger(projectId) || projectId <= 0) {
        throw new TRPCError({ code: 'BAD_REQUEST', message: 'This drawing has no valid project. Select a project and analyze the drawing again before adding rooms.' });
      }
      const [selectedProject] = await db.select({ id: projects.id })
        .from(projects)
        .where(and(eq(projects.id, projectId), eq(projects.userId, ctx.user.id)))
        .limit(1);
      if (!selectedProject) {
        throw new TRPCError({ code: 'FORBIDDEN', message: 'The drawing project is unavailable or does not belong to you.' });
      }

      // Derive bounding box from polygon points for the notNull column
      const xs = input.polygonPoints.map(p => p.x);
      const ys = input.polygonPoints.map(p => p.y);
      const minX = Math.min(...xs);
      const minY = Math.min(...ys);
      const bbox = JSON.stringify({
        x: minX,
        y: minY,
        width: Math.max(...xs) - minX,
        height: Math.max(...ys) - minY,
      });

      const result = await db.insert(detectedRooms).values({
        pageId: input.drawingPageId,
        projectId,
        roomLabel: input.roomLabel,
        boundingBoxJson: bbox,
        polygonJson: input.polygonPoints,
        polygonSource: 'dda_ray_cast',
        polygonExtractedAt: new Date(),
        areaSqm: input.areaM2 != null ? String(input.areaM2) : null,
        areaSqmJson: input.areaM2 != null ? { value: input.areaM2, confirmed: false, source: 'ai-extracted' } : null,
        occupancyGroup: input.occupancyGroup ?? 'C',
        occupancyGroupJson: { value: input.occupancyGroup ?? 'C', confirmed: false, source: 'ai-extracted' },
        spaceType: input.spaceType ?? 'room',
        seedX: input.seedX,
        seedY: input.seedY,
        doorBarriersJson: input.doorBarriers ?? null,
        detectionMethod: 'dda_ray_cast',
        confidence: '1.000',
      } as any);

      computeRoomAdjacency(input.drawingPageId).catch(err =>
        console.error(
          '[AdjacencyService] Post-polygon-save recomputation failed:',
          err,
        )
      );

      return { roomId: result[0].insertId };
    }),

  /** Confirm the occupancy and area facts for a newly saved DDA room. */
  confirmDdaRoomDetails: protectedProcedure
    .input(z.object({
      roomId: z.number().int().positive(),
      occupancyGroup: z.string().trim().min(1).max(10),
      areaM2: z.number().finite().positive(),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: 'DB unavailable' });

      const [room] = await db
        .select({
          roomId: detectedRooms.id,
          drawingId: drawingPages.drawingId,
          projectId: drawingAnalyses.projectId,
        })
        .from(detectedRooms)
        .innerJoin(drawingPages, eq(drawingPages.id, detectedRooms.pageId))
        .innerJoin(drawingAnalyses, eq(drawingAnalyses.id, drawingPages.drawingId))
        .where(and(
          eq(detectedRooms.id, input.roomId),
          eq(drawingAnalyses.userId, ctx.user.id),
          eq(detectedRooms.detectionMethod, 'dda_ray_cast'),
        ))
        .limit(1);

      if (!room) throw new TRPCError({ code: 'FORBIDDEN', message: 'Room not found or access denied.' });
      if (room.projectId == null || !Number.isSafeInteger(room.projectId) || room.projectId <= 0) {
        throw new TRPCError({ code: 'BAD_REQUEST', message: 'This room is not associated with a valid project.' });
      }

      const [project] = await db
        .select({ id: projects.id })
        .from(projects)
        .where(and(eq(projects.id, room.projectId), eq(projects.userId, ctx.user.id)))
        .limit(1);
      if (!project) throw new TRPCError({ code: 'FORBIDDEN', message: 'The room project is unavailable or does not belong to you.' });

      await db
        .update(detectedRooms)
        .set({
          occupancyGroup: input.occupancyGroup,
          occupancyGroupJson: userConfirmedFact(input.occupancyGroup),
          areaSqm: input.areaM2.toFixed(2),
          areaSqmJson: userConfirmedFact(input.areaM2),
          manualOverride: 1,
          lastCorrectedAt: new Date(),
        })
        .where(eq(detectedRooms.id, input.roomId));

      return { roomId: input.roomId, confirmed: true };
    }),

  /** Load persisted measured windows for a drawing page. */
  getMeasuredWindows: protectedProcedure
    .input(z.object({
      projectId: z.number().int().positive(),
      pageId: z.number().int().positive(),
    }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: 'DB unavailable' });

      const [page] = await db
        .select({ pageId: drawingPages.id })
        .from(drawingPages)
        .innerJoin(drawingAnalyses, eq(drawingAnalyses.id, drawingPages.drawingId))
        .where(and(
          eq(drawingPages.id, input.pageId),
          eq(drawingAnalyses.projectId, input.projectId),
          eq(drawingAnalyses.userId, ctx.user.id),
        ))
        .limit(1);
      if (!page) throw new TRPCError({ code: 'FORBIDDEN', message: 'You do not have access to this drawing page.' });

      const rows = await db
        .select()
        .from(measuredWindows)
        .where(and(
          eq(measuredWindows.projectId, input.projectId),
          eq(measuredWindows.pageId, input.pageId),
        ));

      return rows.map(row => ({
        id: String(row.id),
        face: row.face,
        widthMm: Number(row.widthMm),
        heightMm: Number(row.heightMm),
        areaM2: Number(row.areaM2),
        position: safeJsonParse(row.positionJson) as { x: number; y: number },
        pixelWidth: Number(row.pixelWidth),
      }));
    }),

  /** Persist an explicitly measured window for a drawing page. */
  saveMeasuredWindow: protectedProcedure
    .input(z.object({
      projectId: z.number().int().positive(),
      pageId: z.number().int().positive(),
      face: z.enum(['N', 'S', 'E', 'W', 'unknown']),
      widthMm: z.number().positive(),
      heightMm: z.number().positive(),
      areaM2: z.number().positive(),
      position: z.object({ x: z.number(), y: z.number() }),
      pixelWidth: z.number().positive(),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: 'DB unavailable' });

      const [page] = await db
        .select({ pageId: drawingPages.id })
        .from(drawingPages)
        .innerJoin(drawingAnalyses, eq(drawingAnalyses.id, drawingPages.drawingId))
        .where(and(
          eq(drawingPages.id, input.pageId),
          eq(drawingAnalyses.projectId, input.projectId),
          eq(drawingAnalyses.userId, ctx.user.id),
        ))
        .limit(1);
      if (!page) throw new TRPCError({ code: 'FORBIDDEN', message: 'You do not have access to this drawing page.' });

      const result = await db.insert(measuredWindows).values({
        projectId: input.projectId,
        pageId: input.pageId,
        face: input.face,
        widthMm: input.widthMm.toFixed(2),
        heightMm: input.heightMm.toFixed(2),
        areaM2: input.areaM2.toFixed(2),
        positionJson: input.position,
        pixelWidth: input.pixelWidth.toFixed(2),
        provenanceJson: userConfirmedFact(true),
      });

      return { windowId: result[0].insertId };
    }),

  /** Delete one measured window owned through its drawing page. */
  deleteMeasuredWindow: protectedProcedure
    .input(z.object({ windowId: z.number().int().positive() }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: 'DB unavailable' });

      const [windowRow] = await db
        .select({ id: measuredWindows.id })
        .from(measuredWindows)
        .innerJoin(drawingPages, eq(drawingPages.id, measuredWindows.pageId))
        .innerJoin(drawingAnalyses, eq(drawingAnalyses.id, drawingPages.drawingId))
        .where(and(
          eq(measuredWindows.id, input.windowId),
          eq(drawingAnalyses.userId, ctx.user.id),
        ))
        .limit(1);
      if (!windowRow) throw new TRPCError({ code: 'NOT_FOUND', message: 'Measured window not found.' });

      await db.delete(measuredWindows).where(eq(measuredWindows.id, input.windowId));
      return { success: true };
    }),

  /**
   * Save a manual door annotation for a page.
   * Ownership: pageId → drawingAnalyses.userId must equal ctx.user.id
   */
  saveDoorFeature: protectedProcedure
    .input(z.object({
      pageId: z.number().int().positive(),
      geometryJson: z.array(z.object({ x: z.number(), y: z.number() })).min(3),
      roomId: z.number().int().positive().optional(),
      metadataJson: z.record(z.string(), z.any()).optional(),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: 'DB unavailable' });

      const [page] = await db
        .select({ drawingId: drawingPages.drawingId })
        .from(drawingPages)
        .where(eq(drawingPages.id, input.pageId));
      if (!page) throw new TRPCError({ code: 'NOT_FOUND', message: 'Page not found' });

      const [analysisRow] = await db
        .select({ id: drawingAnalyses.id, projectId: drawingAnalyses.projectId })
        .from(drawingAnalyses)
        .where(and(eq(drawingAnalyses.id, page.drawingId), eq(drawingAnalyses.userId, ctx.user.id)));
      if (!analysisRow) throw new TRPCError({ code: 'FORBIDDEN', message: 'Access denied' });

      const xs = input.geometryJson.map(p => p.x);
      const ys = input.geometryJson.map(p => p.y);
      const centroid = {
        x: xs.reduce((sum, value) => sum + value, 0) / xs.length,
        y: ys.reduce((sum, value) => sum + value, 0) / ys.length,
      };

      const result = await db.insert(detectedFeatures).values({
        pageId: input.pageId,
        roomId: input.roomId ?? null,
        featureType: 'door',
        positionJson: centroid,
        geometryJson: input.geometryJson,
        confidence: '1.00',
        metadataJson: input.metadataJson ?? null,
        source: 'manual_annotation',
      } as any);

      return { featureId: result[0].insertId };
    }),

  /**
   * Phase C — load all DDA ray-cast polygons for a page (persisted across sessions).
   */
  getRoomPolygons: protectedProcedure
    .input(z.object({ drawingPageId: z.number().int().positive() }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: 'DB unavailable' });

      const [page] = await db
        .select({ drawingId: drawingPages.drawingId })
        .from(drawingPages)
        .where(eq(drawingPages.id, input.drawingPageId));
      if (!page) throw new TRPCError({ code: 'NOT_FOUND', message: 'Page not found' });

      const [analysisRow] = await db
        .select({ id: drawingAnalyses.id })
        .from(drawingAnalyses)
        .where(and(eq(drawingAnalyses.id, page.drawingId), eq(drawingAnalyses.userId, ctx.user.id)));
      if (!analysisRow) throw new TRPCError({ code: 'FORBIDDEN', message: 'Access denied' });

      const rooms = await db
        .select()
        .from(detectedRooms)
        .where(and(
          eq(detectedRooms.pageId, input.drawingPageId),
          eq(detectedRooms.detectionMethod, 'dda_ray_cast'),
        ));

      return rooms.map(r => ({
        id: r.id,
        roomLabel: r.roomLabel ?? 'Room',
        polygon: (safeJsonParse(r.polygonJson) as Array<{ x: number; y: number }> | null) ?? [],
        seedX: r.seedX ?? 0,
        seedY: r.seedY ?? 0,
        areaM2: readProvenancedFact({ wrapper: r.areaSqmJson, scalar: r.areaSqm ? parseFloat(r.areaSqm as unknown as string) : null, field: 'areaSqm', entityType: 'room', entityId: r.id, isValue: (v): v is number => typeof v === 'number' && Number.isFinite(v) && v >= 0 }).value,
      }));
    }),

  /**
   * Phase D — deterministic calculator orchestration.
   * Runs occupant load, egress window, travel distance, and FRR checks
   * on client-supplied room/window data. No LLM calls.
   */
  runCalculatorOrchestrator: protectedProcedure
    .input(z.object({
      drawingPageId: z.number().int().positive(),
      rooms: z.array(z.object({
        label: z.string(),
        occupancyGroup: z.string(),
        spaceType: z.string().optional(),
        manualOverride: z.boolean().optional(),
        areaM2: z.number().nullable(),
        areaSqmJson: z.unknown().optional(),
        occupancyGroupJson: z.unknown().optional(),
      })),
      windows: z.array(z.object({
        widthMm: z.number(),
        heightMm: z.number(),
        areaM2: z.number(),
      })),
      travelDistanceResults: z.array(z.object({
        roomLabel: z.string(),
        distanceM: z.number(),
        limit: z.number(),
        result: z.string(),
        nbcClause: z.string(),
      })),
      storeys: z.number().int().min(1).max(50),
      sprinklered: z.boolean(),
      province: z.string().max(2),
      calibrationConfidence: z.enum(['high', 'low', 'none']),
      jurisdictionSource: z.enum(['geocoded', 'manual', 'device', 'fallback']).optional(),
      municipality: z.string().max(100).optional(),
      address: z.string().max(500).optional(),
      totalDwellingUnits: z.number().int().positive().optional(),
      stackSeparations: z.array(z.object({
        from: z.string(),
        to: z.string(),
        frr: z.string(),
        hours: z.number(),
        nbcRef: z.string(),
      })).optional(),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: 'DB unavailable' });

      // Ownership check — same pattern as saveRoomPolygon
      const [page] = await db
        .select({ drawingId: drawingPages.drawingId })
        .from(drawingPages)
        .where(eq(drawingPages.id, input.drawingPageId));
      if (!page) throw new TRPCError({ code: 'NOT_FOUND', message: 'Page not found' });

      const [analysisRow] = await db
        .select({ id: drawingAnalyses.id, projectId: drawingAnalyses.projectId })
        .from(drawingAnalyses)
        .where(and(eq(drawingAnalyses.id, page.drawingId), eq(drawingAnalyses.userId, ctx.user.id)));
      if (!analysisRow) throw new TRPCError({ code: 'FORBIDDEN', message: 'Access denied' });

      const [projectRow] = await db.select({
        totalDwellingUnits: projects.totalDwellingUnits,
        totalDwellingUnitsJson: projects.totalDwellingUnitsJson,
        stackConfirmedAt: projects.stackConfirmedAt,
      })
        .from(projects).where(eq(projects.id, analysisRow.projectId)).limit(1);
      const projectUnits = readProvenancedFact({ wrapper: projectRow?.totalDwellingUnitsJson, scalar: projectRow?.totalDwellingUnits, field: 'totalDwellingUnits', entityType: 'project', entityId: analysisRow.projectId, isValue: (v): v is number => typeof v === 'number' && Number.isInteger(v) && v >= 0 }).value ?? undefined;
      const result = runCalculatorOrchestrator({
        ...input,
        projectId: analysisRow.projectId,
        totalDwellingUnits: projectUnits,
        stackConfirmedAt: projectRow?.stackConfirmedAt ?? null,
      }, input.province);
      const frrCandidates = result.complianceRequirements.filter(c => c.requirementType.startsWith('orchestrator-frr.'));
      const occupantLoadCandidates = result.complianceRequirements.filter(c => c.requirementType.startsWith('orchestrator-occupant-load.'));
      const complianceGraph = await persistRequirementGraph(analysisRow.projectId, frrCandidates, "frr");
      const occupantLoadGraph = await persistRequirementGraph(analysisRow.projectId, occupantLoadCandidates, "occupant-load");
      return { ...result, complianceGraph, occupantLoadGraph };
    }),
});
