DROP TABLE `auditModificationHistory`;--> statement-breakpoint
DROP TABLE `auditSignatures`;--> statement-breakpoint
DROP TABLE `batchComparisons`;--> statement-breakpoint
DROP TABLE `collaborationAuditLog`;--> statement-breakpoint
DROP TABLE `complianceAuditLog`;--> statement-breakpoint
DROP TABLE `complianceAuditTrail`;--> statement-breakpoint
DROP TABLE `complianceEvaluationResults`;--> statement-breakpoint
DROP TABLE `customRules`;--> statement-breakpoint
DROP TABLE `disclaimerAcknowledgments`;--> statement-breakpoint
DROP TABLE `drawingAnalyses`;--> statement-breakpoint
DROP TABLE `drawingDataExtractions`;--> statement-breakpoint
DROP TABLE `nbcRules`;--> statement-breakpoint
DROP TABLE `projectShares`;--> statement-breakpoint
DROP TABLE `reports`;--> statement-breakpoint
DROP TABLE `ruleApplications`;--> statement-breakpoint
DROP TABLE `ruleAuditTrail`;--> statement-breakpoint
DROP TABLE `rulesDatabase`;--> statement-breakpoint
DROP TABLE `rulesLibrary`;--> statement-breakpoint
DROP TABLE `scenarioHistory`;--> statement-breakpoint
DROP TABLE `scenarios`;--> statement-breakpoint
ALTER TABLE `signatureLogs` MODIFY COLUMN `status` enum('success','failure') NOT NULL;