CREATE TABLE `energyDataExtractions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`drawingAnalysisId` int NOT NULL,
	`energyFeatures` text NOT NULL,
	`structuralFeatures` text,
	`modelUsed` varchar(100) NOT NULL,
	`modelVersion` varchar(50),
	`extractionConfidence` decimal(3,2) NOT NULL,
	`ipAddress` varchar(45),
	`userAgent` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `energyDataExtractions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `energyFeatures` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`drawingAnalysisId` int,
	`envelopeArea` decimal(10,2),
	`windowAreas` text NOT NULL,
	`wallAreas` text NOT NULL,
	`roofArea` decimal(10,2),
	`roofRValue` decimal(6,2),
	`foundationType` varchar(50),
	`foundationRValue` decimal(6,2),
	`mechanicalRoomLocation` varchar(100),
	`proposedHeatingSystem` varchar(100),
	`proposedCoolingSystem` varchar(100),
	`proposedVentilationSystem` varchar(100),
	`solarReadyZone` boolean DEFAULT false,
	`evReady` boolean DEFAULT false,
	`extractionConfidence` decimal(3,2),
	`manuallyVerified` boolean DEFAULT false,
	`verifiedBy` int,
	`verifiedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `energyFeatures_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `jurisdictionProfiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`province` enum('AB','BC','ON','SK','MB') NOT NULL,
	`municipality` varchar(100),
	`climateZone` varchar(10) NOT NULL,
	`heatingDegreeDays` int,
	`designTemperatureWinter` int,
	`designTemperatureSummer` int,
	`seismicZone` varchar(20),
	`spectralAccelerationSa02` decimal(4,3),
	`spectralAccelerationSa05` decimal(4,3),
	`spectralAccelerationSa10` decimal(4,3),
	`stepCodeAdopted` boolean DEFAULT false,
	`currentStepCodeTier` enum('1','2','3','4','5'),
	`stepCodeEffectiveDate` date,
	`nbcEdition` varchar(20) NOT NULL,
	`localAmendments` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `jurisdictionProfiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `professionalSeals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`engineerName` varchar(255) NOT NULL,
	`licenseNumber` varchar(100) NOT NULL,
	`association` varchar(100) NOT NULL,
	`associationProvince` varchar(50),
	`sealImageUrl` varchar(500),
	`licenseExpiry` date,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `professionalSeals_id` PRIMARY KEY(`id`),
	CONSTRAINT `professionalSeals_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `stepCodeAnalyses` (
	`id` varchar(36) NOT NULL,
	`projectId` int NOT NULL,
	`userId` int NOT NULL,
	`energyFeaturesId` int NOT NULL,
	`jurisdictionProfileId` int NOT NULL,
	`stepCodeTierId` int NOT NULL,
	`tierTarget` varchar(10) NOT NULL,
	`tierAchieved` varchar(10),
	`tediTarget` decimal(6,2) NOT NULL,
	`tediModelled` decimal(6,2) NOT NULL,
	`tediCompliant` boolean NOT NULL,
	`tediGap` decimal(6,2),
	`teuiTarget` decimal(6,2) NOT NULL,
	`teuiModelled` decimal(6,2) NOT NULL,
	`teuiCompliant` boolean NOT NULL,
	`teuiGap` decimal(6,2),
	`airtightnessTarget` decimal(4,2),
	`airtightnessModelled` decimal(4,2),
	`airtightnessCompliant` boolean,
	`mechEfficiencyTarget` decimal(4,2),
	`mechEfficiencyModelled` decimal(4,2),
	`mechEfficiencyCompliant` boolean,
	`overallCompliant` boolean NOT NULL,
	`complianceStatus` enum('pass','fail','conditional') NOT NULL,
	`prescriptiveApplicable` boolean DEFAULT false,
	`prescriptiveDescription` text,
	`prescriptiveRequirements` text,
	`recommendations` text,
	`cryptographicSignature` text NOT NULL,
	`signatureVerified` boolean NOT NULL DEFAULT false,
	`ipAddress` varchar(45),
	`userAgent` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`immutable` boolean NOT NULL DEFAULT true,
	CONSTRAINT `stepCodeAnalyses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `stepCodeTiers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tier` enum('1','2','3','4','5') NOT NULL,
	`buildingType` varchar(50) NOT NULL,
	`climateZone` varchar(10) NOT NULL,
	`tediTarget` decimal(6,2) NOT NULL,
	`teuiTarget` decimal(6,2) NOT NULL,
	`mechEfficiencyMin` decimal(4,2),
	`airtightnessMax` decimal(4,2),
	`codeReference` varchar(255),
	`effectiveDate` date NOT NULL,
	`retiredDate` date,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `stepCodeTiers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `uiTranslations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`key` varchar(255) NOT NULL,
	`en` text NOT NULL,
	`fr` text,
	`context` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `uiTranslations_id` PRIMARY KEY(`id`),
	CONSTRAINT `uiTranslations_key_unique` UNIQUE(`key`)
);
