/**
 * SharedProjectView — public shared project viewer
 * SHARING-002: /shared/:token — no auth required
 *
 * Note: trpc.projects.get is protectedProcedure; this page shows
 * only what accessSharedProject returns (projectId + accessLevel).
 */

import { useParams } from "wouter";
import { trpc } from "@/lib/trpc";

export default function SharedProjectView() {
  const params = useParams<{ token: string }>();
  const token = params?.token ?? "";

  const { data, isLoading, error } =
    trpc.sharing.accessSharedProject.useQuery(
      { token },
      { enabled: !!token, retry: false },
    );

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <p className="text-muted-foreground">Loading shared project...</p>
      </div>
    );
  }

  if (error) {
    const msg = error.message ?? "";
    let heading = "Link unavailable";
    let detail = "This share link is not valid.";
    if (msg.includes("expired"))  { heading = "Link expired";          detail = "This share link has expired."; }
    if (msg.includes("inactive")) { heading = "Link deactivated";      detail = "This share link has been deactivated by its owner."; }
    if (msg.includes("limit"))    { heading = "Access limit reached";  detail = "This share link has reached its maximum number of uses."; }
    if (msg.includes("Invalid"))  { heading = "Invalid link";          detail = "This share link doesn't exist or has been removed."; }

    return (
      <div className="min-h-screen flex flex-col items-center justify-center gap-4 text-center px-4">
        <div className="text-4xl">🔒</div>
        <h1 className="text-2xl font-bold">{heading}</h1>
        <p className="text-muted-foreground max-w-sm">{detail}</p>
        <p className="text-sm text-muted-foreground">
          Contact the person who sent you this link for a new one.
        </p>
      </div>
    );
  }

  if (!data) return null;

  return (
    <div className="min-h-screen bg-background">
      {/* Read-only header banner */}
      <div className="bg-amber-50 border-b border-amber-200 px-6 py-3 flex items-center justify-between">
        <div className="flex items-center gap-2 text-sm text-amber-800">
          <span>🔗</span>
          <span>
            You are viewing a shared project in{" "}
            <strong>
              {data.accessLevel === "view_only" ? "read-only" :
               data.accessLevel === "comment"   ? "comment"  :
               "download"} mode
            </strong>
          </span>
        </div>
        <a
          href="https://complycode.ca"
          className="text-xs text-amber-700 underline"
        >
          Powered by CodeComply
        </a>
      </div>

      {/* Project info */}
      <div className="container mx-auto px-4 py-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold mb-2">
            Shared Project #{data.projectId}
          </h1>
        </div>

        <div className="grid gap-6">
          {/* Project summary card */}
          <div className="border border-border rounded-lg p-6">
            <h2 className="text-lg font-semibold mb-4">Project Summary</h2>
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <p className="text-muted-foreground">Project ID</p>
                <p className="font-medium">{data.projectId}</p>
              </div>
              <div>
                <p className="text-muted-foreground">Access Level</p>
                <p className="font-medium capitalize">
                  {data.accessLevel.replace("_", " ")}
                </p>
              </div>
            </div>
          </div>

          {/* Download access: show export note */}
          {data.accessLevel === "download" && (
            <div className="border border-border rounded-lg p-6">
              <h2 className="text-lg font-semibold mb-4">Downloads</h2>
              <p className="text-sm text-muted-foreground mb-4">
                You have download access to this project's reports.
              </p>
              <p className="text-sm text-muted-foreground italic">
                Report download will be available here once generated by the project owner.
              </p>
            </div>
          )}

          {/* Powered by footer */}
          <div className="text-center text-xs text-muted-foreground pt-4">
            <p>
              This project is shared via{" "}
              <a href="https://complycode.ca" className="underline">
                CodeComply
              </a>{" "}
              — Canadian building code compliance platform.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
