CREATE TABLE IF NOT EXISTS codeStrategies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  projectId INT NOT NULL,
  orgId INT,
  createdBy INT NOT NULL,
  province VARCHAR(5) NOT NULL,
  codeEdition VARCHAR(20) NOT NULL,
  constructionType VARCHAR(10) NOT NULL,
  sprinklered TINYINT(1) DEFAULT 0,
  buildingHeightM DECIMAL(6,2),
  buildingAreaM2 DECIMAL(10,2),
  storeys INT,
  occupancyGroups JSON,
  egressStrategy TEXT,
  exitCount INT,
  separationRequired TINYINT(1) DEFAULT 0,
  strategySummaryJson JSON,
  approvedBy INT,
  approvedAt TIMESTAMP NULL,
  status ENUM('draft','approved','superseded') DEFAULT 'draft',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_projectId (projectId),
  INDEX idx_orgId (orgId)
);
