CREATE TABLE IF NOT EXISTS `calculationsPackages` (
  `id` int NOT NULL AUTO_INCREMENT,
  `projectId` int NOT NULL,
  `orgId` int,
  `createdBy` int NOT NULL,
  `drawingAnalysisId` int,
  `codeStrategyId` int,
  `province` varchar(5) NOT NULL,
  `codeEdition` varchar(20) NOT NULL,
  `sprinklered` tinyint DEFAULT 0,
  `occupantLoadByGroup` json,
  `totalOccupantLoad` int,
  `exitWidthRequiredMm` decimal(8,2),
  `travelDistanceResults` json,
  `areaByFloor` json,
  `totalAreaM2` decimal(10,2),
  `nbcTableRef` varchar(50),
  `calculationsSummaryJson` json,
  `approvedBy` int,
  `approvedAt` timestamp NULL,
  `status` enum('draft','approved','superseded') DEFAULT 'draft',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
