CREATE TABLE fireAssemblies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  drawingAnalysisId INT NOT NULL,
  pageId INT NOT NULL,
  projectId INT NOT NULL,
  assemblyType ENUM('none','0.5hr','1hr','1.5hr','2hr','fire_separation') NOT NULL,
  frrDrawn DECIMAL(4,2) NOT NULL,
  frrRequired DECIMAL(4,2),
  isCompliant BOOLEAN,
  gap DECIMAL(4,2),
  roomAId INT,
  roomBId INT,
  occupancyA VARCHAR(10),
  occupancyB VARCHAR(10),
  labelA VARCHAR(100),
  labelB VARCHAR(100),
  lengthPx DECIMAL(10,2),
  lengthM DECIMAL(8,2),
  wallHeightM DECIMAL(6,2) DEFAULT 2.74,
  pointsJson JSON NOT NULL,
  nbcReference VARCHAR(50) DEFAULT 'NBC Table 3.1.3.4',
  remediationJson JSON,
  assemblyLabel VARCHAR(10),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_projectId (projectId),
  INDEX idx_drawingAnalysisId (drawingAnalysisId)
);
