import { db } from "../_core/db";
import { jurisdictionProfiles } from "../../drizzle/schema";

export async function seedJurisdictionProfiles() {
  await db.insert(jurisdictionProfiles).values([

    // ─── ALBERTA (NBC(AE) 2023) ───────────────────────────────────────
    { province: "AB", municipality: "Calgary", climateZone: "6A", heatingDegreeDays: 5000, designTemperatureWinter: -33, designTemperatureSummer: 29, seismicZone: "Low", spectralAccelerationSa02: "0.120", spectralAccelerationSa05: "0.075", spectralAccelerationSa10: "0.044", stepCodeAdopted: false, nbcEdition: "2023", isActive: true },
    { province: "AB", municipality: "Edmonton", climateZone: "7A", heatingDegreeDays: 5620, designTemperatureWinter: -34, designTemperatureSummer: 27, seismicZone: "Low", spectralAccelerationSa02: "0.085", spectralAccelerationSa05: "0.052", spectralAccelerationSa10: "0.030", stepCodeAdopted: false, nbcEdition: "2023", isActive: true },
    { province: "AB", municipality: "Red Deer", climateZone: "7A", heatingDegreeDays: 5330, designTemperatureWinter: -34, designTemperatureSummer: 27, seismicZone: "Low", spectralAccelerationSa02: "0.090", spectralAccelerationSa05: "0.057", spectralAccelerationSa10: "0.033", stepCodeAdopted: false, nbcEdition: "2023", isActive: true },
    { province: "AB", municipality: "Lethbridge", climateZone: "6A", heatingDegreeDays: 4200, designTemperatureWinter: -28, designTemperatureSummer: 31, seismicZone: "Low", spectralAccelerationSa02: "0.100", spectralAccelerationSa05: "0.063", spectralAccelerationSa10: "0.037", stepCodeAdopted: false, nbcEdition: "2023", isActive: true },
    { province: "AB", municipality: "Airdrie", climateZone: "6A", heatingDegreeDays: 5000, designTemperatureWinter: -33, designTemperatureSummer: 28, seismicZone: "Low", spectralAccelerationSa02: "0.120", spectralAccelerationSa05: "0.075", spectralAccelerationSa10: "0.044", stepCodeAdopted: false, nbcEdition: "2023", isActive: true },
    { province: "AB", municipality: "High River", climateZone: "6A", heatingDegreeDays: 4800, designTemperatureWinter: -32, designTemperatureSummer: 29, seismicZone: "Low", spectralAccelerationSa02: "0.115", spectralAccelerationSa05: "0.072", spectralAccelerationSa10: "0.042", stepCodeAdopted: false, nbcEdition: "2023", isActive: true },
    { province: "AB", municipality: "Medicine Hat", climateZone: "6A", heatingDegreeDays: 4100, designTemperatureWinter: -28, designTemperatureSummer: 33, seismicZone: "Low", spectralAccelerationSa02: "0.088", spectralAccelerationSa05: "0.055", spectralAccelerationSa10: "0.032", stepCodeAdopted: false, nbcEdition: "2023", isActive: true },
    { province: "AB", municipality: "Grande Prairie", climateZone: "7A", heatingDegreeDays: 6100, designTemperatureWinter: -38, designTemperatureSummer: 26, seismicZone: "Low", spectralAccelerationSa02: "0.070", spectralAccelerationSa05: "0.044", spectralAccelerationSa10: "0.026", stepCodeAdopted: false, nbcEdition: "2023", isActive: true },
    { province: "AB", municipality: "Fort McMurray", climateZone: "7B", heatingDegreeDays: 6900, designTemperatureWinter: -41, designTemperatureSummer: 27, seismicZone: "Low", spectralAccelerationSa02: "0.060", spectralAccelerationSa05: "0.038", spectralAccelerationSa10: "0.022", stepCodeAdopted: false, nbcEdition: "2023", isActive: true },
    { province: "AB", municipality: "Leduc", climateZone: "7A", heatingDegreeDays: 5620, designTemperatureWinter: -34, designTemperatureSummer: 27, seismicZone: "Low", spectralAccelerationSa02: "0.085", spectralAccelerationSa05: "0.052", spectralAccelerationSa10: "0.030", stepCodeAdopted: false, nbcEdition: "2023", isActive: true },

    // ─── BRITISH COLUMBIA (BCBC 2024) ─────────────────────────────────
    { province: "BC", municipality: "Vancouver", climateZone: "4A", heatingDegreeDays: 2825, designTemperatureWinter: -7, designTemperatureSummer: 28, seismicZone: "Very High", spectralAccelerationSa02: "0.940", spectralAccelerationSa05: "0.640", spectralAccelerationSa10: "0.330", stepCodeAdopted: true, currentStepCodeTier: "3", stepCodeEffectiveDate: "2023-05-01", nbcEdition: "2024", isActive: true },
    { province: "BC", municipality: "Surrey", climateZone: "4A", heatingDegreeDays: 2825, designTemperatureWinter: -7, designTemperatureSummer: 28, seismicZone: "Very High", spectralAccelerationSa02: "0.900", spectralAccelerationSa05: "0.610", spectralAccelerationSa10: "0.310", stepCodeAdopted: true, currentStepCodeTier: "3", stepCodeEffectiveDate: "2023-05-01", nbcEdition: "2024", isActive: true },
    { province: "BC", municipality: "Burnaby", climateZone: "4A", heatingDegreeDays: 2825, designTemperatureWinter: -7, designTemperatureSummer: 28, seismicZone: "Very High", spectralAccelerationSa02: "0.920", spectralAccelerationSa05: "0.625", spectralAccelerationSa10: "0.320", stepCodeAdopted: true, currentStepCodeTier: "3", stepCodeEffectiveDate: "2023-05-01", nbcEdition: "2024", isActive: true },
    { province: "BC", municipality: "Richmond", climateZone: "4A", heatingDegreeDays: 2825, designTemperatureWinter: -6, designTemperatureSummer: 27, seismicZone: "Very High", spectralAccelerationSa02: "0.910", spectralAccelerationSa05: "0.615", spectralAccelerationSa10: "0.315", stepCodeAdopted: true, currentStepCodeTier: "3", stepCodeEffectiveDate: "2023-05-01", nbcEdition: "2024", isActive: true },
    { province: "BC", municipality: "Kelowna", climateZone: "5A", heatingDegreeDays: 3200, designTemperatureWinter: -18, designTemperatureSummer: 33, seismicZone: "Intermediate", spectralAccelerationSa02: "0.280", spectralAccelerationSa05: "0.180", spectralAccelerationSa10: "0.110", stepCodeAdopted: true, currentStepCodeTier: "2", stepCodeEffectiveDate: "2023-05-01", nbcEdition: "2024", isActive: true },
    { province: "BC", municipality: "Abbotsford", climateZone: "4A", heatingDegreeDays: 2900, designTemperatureWinter: -10, designTemperatureSummer: 29, seismicZone: "High", spectralAccelerationSa02: "0.650", spectralAccelerationSa05: "0.440", spectralAccelerationSa10: "0.230", stepCodeAdopted: true, currentStepCodeTier: "2", stepCodeEffectiveDate: "2023-05-01", nbcEdition: "2024", isActive: true },
    { province: "BC", municipality: "Victoria", climateZone: "4A", heatingDegreeDays: 2650, designTemperatureWinter: -6, designTemperatureSummer: 25, seismicZone: "High", spectralAccelerationSa02: "0.680", spectralAccelerationSa05: "0.460", spectralAccelerationSa10: "0.240", stepCodeAdopted: true, currentStepCodeTier: "3", stepCodeEffectiveDate: "2023-05-01", nbcEdition: "2024", isActive: true },
    { province: "BC", municipality: "Kamloops", climateZone: "5B", heatingDegreeDays: 3500, designTemperatureWinter: -22, designTemperatureSummer: 35, seismicZone: "Intermediate", spectralAccelerationSa02: "0.240", spectralAccelerationSa05: "0.155", spectralAccelerationSa10: "0.095", stepCodeAdopted: true, currentStepCodeTier: "2", stepCodeEffectiveDate: "2023-05-01", nbcEdition: "2024", isActive: true },
    { province: "BC", municipality: "Prince George", climateZone: "7A", heatingDegreeDays: 5700, designTemperatureWinter: -38, designTemperatureSummer: 27, seismicZone: "Low", spectralAccelerationSa02: "0.120", spectralAccelerationSa05: "0.077", spectralAccelerationSa10: "0.046", stepCodeAdopted: true, currentStepCodeTier: "2", stepCodeEffectiveDate: "2023-05-01", nbcEdition: "2024", isActive: true },
    { province: "BC", municipality: "Nanaimo", climateZone: "4A", heatingDegreeDays: 2750, designTemperatureWinter: -7, designTemperatureSummer: 27, seismicZone: "High", spectralAccelerationSa02: "0.580", spectralAccelerationSa05: "0.390", spectralAccelerationSa10: "0.210", stepCodeAdopted: true, currentStepCodeTier: "2", stepCodeEffectiveDate: "2023-05-01", nbcEdition: "2024", isActive: true },

    // ─── ONTARIO (NBC(ON) 2020) ───────────────────────────────────────
    { province: "ON", municipality: "Toronto", climateZone: "5A", heatingDegreeDays: 3520, designTemperatureWinter: -20, designTemperatureSummer: 31, seismicZone: "Low", spectralAccelerationSa02: "0.200", spectralAccelerationSa05: "0.130", spectralAccelerationSa10: "0.076", stepCodeAdopted: false, nbcEdition: "2020", isActive: true },
    { province: "ON", municipality: "Mississauga", climateZone: "5A", heatingDegreeDays: 3520, designTemperatureWinter: -20, designTemperatureSummer: 31, seismicZone: "Low", spectralAccelerationSa02: "0.195", spectralAccelerationSa05: "0.127", spectralAccelerationSa10: "0.074", stepCodeAdopted: false, nbcEdition: "2020", isActive: true },
    { province: "ON", municipality: "Brampton", climateZone: "5A", heatingDegreeDays: 3520, designTemperatureWinter: -20, designTemperatureSummer: 31, seismicZone: "Low", spectralAccelerationSa02: "0.195", spectralAccelerationSa05: "0.127", spectralAccelerationSa10: "0.074", stepCodeAdopted: false, nbcEdition: "2020", isActive: true },
    { province: "ON", municipality: "Barrie", climateZone: "6A", heatingDegreeDays: 4200, designTemperatureWinter: -24, designTemperatureSummer: 29, seismicZone: "Low", spectralAccelerationSa02: "0.170", spectralAccelerationSa05: "0.110", spectralAccelerationSa10: "0.064", stepCodeAdopted: false, nbcEdition: "2020", isActive: true },
    { province: "ON", municipality: "Pickering", climateZone: "5A", heatingDegreeDays: 3520, designTemperatureWinter: -20, designTemperatureSummer: 30, seismicZone: "Low", spectralAccelerationSa02: "0.198", spectralAccelerationSa05: "0.129", spectralAccelerationSa10: "0.075", stepCodeAdopted: false, nbcEdition: "2020", isActive: true },
    { province: "ON", municipality: "Markham", climateZone: "5A", heatingDegreeDays: 3520, designTemperatureWinter: -20, designTemperatureSummer: 31, seismicZone: "Low", spectralAccelerationSa02: "0.198", spectralAccelerationSa05: "0.129", spectralAccelerationSa10: "0.075", stepCodeAdopted: false, nbcEdition: "2020", isActive: true },
    { province: "ON", municipality: "Vaughan", climateZone: "5A", heatingDegreeDays: 3520, designTemperatureWinter: -20, designTemperatureSummer: 31, seismicZone: "Low", spectralAccelerationSa02: "0.195", spectralAccelerationSa05: "0.127", spectralAccelerationSa10: "0.074", stepCodeAdopted: false, nbcEdition: "2020", isActive: true },
    { province: "ON", municipality: "Oakville", climateZone: "5A", heatingDegreeDays: 3400, designTemperatureWinter: -19, designTemperatureSummer: 30, seismicZone: "Low", spectralAccelerationSa02: "0.190", spectralAccelerationSa05: "0.124", spectralAccelerationSa10: "0.072", stepCodeAdopted: false, nbcEdition: "2020", isActive: true },
    { province: "ON", municipality: "Hamilton", climateZone: "5A", heatingDegreeDays: 3300, designTemperatureWinter: -18, designTemperatureSummer: 30, seismicZone: "Low", spectralAccelerationSa02: "0.185", spectralAccelerationSa05: "0.120", spectralAccelerationSa10: "0.070", stepCodeAdopted: false, nbcEdition: "2020", isActive: true },
    { province: "ON", municipality: "London", climateZone: "5A", heatingDegreeDays: 3600, designTemperatureWinter: -20, designTemperatureSummer: 31, seismicZone: "Low", spectralAccelerationSa02: "0.160", spectralAccelerationSa05: "0.104", spectralAccelerationSa10: "0.061", stepCodeAdopted: false, nbcEdition: "2020", isActive: true },
    { province: "ON", municipality: "Ottawa", climateZone: "6A", heatingDegreeDays: 4440, designTemperatureWinter: -27, designTemperatureSummer: 30, seismicZone: "Intermediate", spectralAccelerationSa02: "0.420", spectralAccelerationSa05: "0.270", spectralAccelerationSa10: "0.158", stepCodeAdopted: false, nbcEdition: "2020", isActive: true },
    { province: "ON", municipality: "Kingston", climateZone: "6A", heatingDegreeDays: 4100, designTemperatureWinter: -24, designTemperatureSummer: 29, seismicZone: "Intermediate", spectralAccelerationSa02: "0.380", spectralAccelerationSa05: "0.245", spectralAccelerationSa10: "0.143", stepCodeAdopted: false, nbcEdition: "2020", isActive: true },

  ]).onDuplicateKeyUpdate({ set: { isActive: true } });

  console.log("jurisdictionProfiles seeded: 31 rows (AB x10, BC x10, ON x11)");
}
