/**
 * AnalysisStatusBanner Component
 *
 * Displays analysis status with appropriate visual styling and information.
 *
 * Status Types:
 * - DRAFT: Amber banner, preliminary analysis
 * - UNDER_REVIEW: Blue banner, awaiting professional review
 * - VALID: Green banner with professional credentials
 * - REJECTED: Red banner with rejection reason
 */

import { AlertCircle, CheckCircle2, Clock, XCircle } from 'lucide-react';
import { Card } from '@/components/ui/card';

export type AnalysisStatus = 'DRAFT' | 'UNDER_REVIEW' | 'VALID' | 'REJECTED';

interface AnalysisStatusBannerProps {
  status: AnalysisStatus;
  validatedAt?: Date;
  validatedByName?: string;
  validatedByLicenseNumber?: string;
  validatedByAssociation?: string;
  rejectionReason?: string;
}

export function AnalysisStatusBanner({
  status,
  validatedAt,
  validatedByName,
  validatedByLicenseNumber,
  validatedByAssociation,
  rejectionReason,
}: AnalysisStatusBannerProps) {
  const getStatusConfig = () => {
    switch (status) {
      case 'DRAFT':
        return {
          backgroundColor: 'bg-amber-50',
          borderColor: 'border-amber-300',
          textColor: 'text-amber-900',
          icon: AlertCircle,
          iconColor: 'text-amber-600',
          title: 'Preliminary AI Analysis',
          subtitle: 'Awaiting Professional Review',
          description:
            'This analysis has been generated by AI and requires review and acceptance by a licensed Professional Engineer or Architect before it has any legal validity.',
        };

      case 'UNDER_REVIEW':
        return {
          backgroundColor: 'bg-blue-50',
          borderColor: 'border-blue-300',
          textColor: 'text-blue-900',
          icon: Clock,
          iconColor: 'text-blue-600',
          title: 'Under Professional Review',
          subtitle: 'Awaiting Acceptance',
          description: 'A licensed professional is currently reviewing this analysis.',
        };

      case 'VALID':
        return {
          backgroundColor: 'bg-green-50',
          borderColor: 'border-green-300',
          textColor: 'text-green-900',
          icon: CheckCircle2,
          iconColor: 'text-green-600',
          title: 'Professional Certified',
          subtitle: 'Analysis Accepted',
          description: 'This analysis has been reviewed and accepted by a licensed professional.',
        };

      case 'REJECTED':
        return {
          backgroundColor: 'bg-red-50',
          borderColor: 'border-red-300',
          textColor: 'text-red-900',
          icon: XCircle,
          iconColor: 'text-red-600',
          title: 'Analysis Rejected',
          subtitle: 'Professional Review Failed',
          description: rejectionReason || 'This analysis was rejected by the reviewing professional.',
        };

      default:
        return {
          backgroundColor: 'bg-gray-50',
          borderColor: 'border-gray-300',
          textColor: 'text-gray-900',
          icon: AlertCircle,
          iconColor: 'text-gray-600',
          title: 'Unknown Status',
          subtitle: 'Status Unknown',
          description: 'Unable to determine analysis status.',
        };
    }
  };

  const config = getStatusConfig();
  const Icon = config.icon;

  return (
    <Card
      className={`${config.backgroundColor} border-2 ${config.borderColor} ${config.textColor} p-6 mb-6`}
    >
      <div className="space-y-4">
        {/* Header with Icon */}
        <div className="flex items-start gap-4">
          <Icon className={`w-8 h-8 ${config.iconColor} flex-shrink-0 mt-1`} />
          <div className="flex-1">
            <h2 className="text-xl font-bold">{config.title}</h2>
            <p className="text-sm font-semibold opacity-90">{config.subtitle}</p>
          </div>
        </div>

        {/* Description */}
        <p className="text-sm leading-relaxed">{config.description}</p>

        {/* Professional Details (for VALID status) */}
        {status === 'VALID' && validatedByName && (
          <div className="bg-white/50 rounded-lg p-4 space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="font-semibold">Professional:</span>
              <span>{validatedByName}</span>
            </div>
            {validatedByLicenseNumber && (
              <div className="flex justify-between">
                <span className="font-semibold">License Number:</span>
                <span className="font-mono">{validatedByLicenseNumber}</span>
              </div>
            )}
            {validatedByAssociation && (
              <div className="flex justify-between">
                <span className="font-semibold">Association:</span>
                <span>{validatedByAssociation}</span>
              </div>
            )}
            {validatedAt && (
              <div className="flex justify-between">
                <span className="font-semibold">Accepted:</span>
                <span>{new Date(validatedAt).toLocaleString()}</span>
              </div>
            )}
          </div>
        )}

        {/* Rejection Details (for REJECTED status) */}
        {status === 'REJECTED' && rejectionReason && (
          <div className="bg-white/50 rounded-lg p-4 text-sm">
            <p className="font-semibold mb-2">Rejection Reason:</p>
            <p className="whitespace-pre-wrap">{rejectionReason}</p>
          </div>
        )}

        {/* Legal Notice */}
        <div className="bg-white/30 rounded-lg p-3 text-xs border-l-4 border-current">
          <p className="font-semibold mb-1">Legal Notice:</p>
          <p>
            {status === 'VALID'
              ? 'This analysis has been professionally certified and may be used for regulatory submission. However, you remain responsible for verifying compliance with all applicable codes and regulations.'
              : 'This analysis is not legally defensible until it has been reviewed and accepted by a licensed Professional Engineer or Architect.'}
          </p>
        </div>
      </div>
    </Card>
  );
}
