import { useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Download, FileText, Check, AlertCircle } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";

interface StepCodeReportProps {
  projectId: number;
  analysisId?: string;
  language?: "en" | "fr";
  onReportGenerated?: (url: string) => void;
}

export function StepCodeReport({
  projectId,
  analysisId = undefined,
  language = "en",
  onReportGenerated,
}: StepCodeReportProps) {
  const { user } = useAuth();
  const [isGenerating, setIsGenerating] = useState(false);
  const [didGenerate, setDidGenerate] = useState(false);

  const { data: analysis, isLoading } = trpc.stepCode.getAnalyses.useQuery({ projectId });
  const { data: project } = trpc.projects.get.useQuery({ id: projectId });

  const saveResult = trpc.projectsLegacy.calculatorResults.save.useMutation();

  const currentAnalysis = analysis?.[analysis.length - 1] ?? null;

  const t = {
    en: {
      title: "BC Energy Step Code Compliance Report",
      projectName: "Project Name",
      address: "Address",
      complianceAnalysis: "Compliance Analysis",
      tierTarget: "Step Code Tier Target",
      tierAchieved: "Tier Achieved",
      compliant: "Compliant",
      nonCompliant: "Non-Compliant",
      tediAnalysis: "TEDI (Thermal Energy Demand Intensity)",
      teuiAnalysis: "TEUI (Thermal Energy Use Intensity)",
      target: "Target",
      modelled: "Modelled",
      gap: "Gap",
      recommendations: "Recommendations for Improvement",
      auditTrail: "Immutable Audit Trail",
      signatureVerified: "Signature Verified",
      generatedAt: "Generated",
      generatedBy: "Generated By",
      generateReport: "Generate PDF Report",
      generating: "Generating...",
      downloaded: "PDF Downloaded",
      regulatoryReference: "Regulatory Reference: BC Housing 2017 Step Code Metrics, NBC 2024",
    },
    fr: {
      title: "Rapport de Conformité du Code d'Énergie de la Colombie-Britannique",
      projectName: "Nom du Projet",
      address: "Adresse",
      complianceAnalysis: "Analyse de Conformité",
      tierTarget: "Niveau Cible du Code d'Énergie",
      tierAchieved: "Niveau Atteint",
      compliant: "Conforme",
      nonCompliant: "Non Conforme",
      tediAnalysis: "TEDI (Intensité de la Demande d'Énergie Thermique)",
      teuiAnalysis: "TEUI (Intensité d'Utilisation d'Énergie Thermique)",
      target: "Cible",
      modelled: "Modélisé",
      gap: "Écart",
      recommendations: "Recommandations pour l'Amélioration",
      auditTrail: "Piste d'Audit Immuable",
      signatureVerified: "Signature Vérifiée",
      generatedAt: "Généré",
      generatedBy: "Généré par",
      generateReport: "Générer le Rapport PDF",
      generating: "Génération...",
      downloaded: "PDF Téléchargé",
      regulatoryReference:
        "Référence Réglementaire: Métriques du Code d'Énergie 2017 de la Colombie-Britannique, NBC 2024",
    },
  };

  const labels = t[language];

  const handleGenerateReport = async () => {
    if (!currentAnalysis) return;
    setIsGenerating(true);

    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      let y = 20;

      // Title
      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      doc.text(labels.title, pageWidth / 2, y, { align: "center" });
      y += 10;

      // Compliance status banner
      doc.setFontSize(12);
      doc.setTextColor(currentAnalysis.overallCompliant ? 22 : 185, currentAnalysis.overallCompliant ? 163 : 28, currentAnalysis.overallCompliant ? 74 : 28);
      doc.text(
        currentAnalysis.overallCompliant ? labels.compliant.toUpperCase() : labels.nonCompliant.toUpperCase(),
        pageWidth / 2,
        y,
        { align: "center" }
      );
      doc.setTextColor(0, 0, 0);
      y += 10;

      // Project info
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.text("Project Information", 14, y);
      y += 6;
      doc.setFont("helvetica", "normal");
      doc.text(`${labels.projectName}: ${project?.name ?? "N/A"}`, 14, y);
      y += 5;
      doc.text(`${labels.address}: ${project?.address ?? "N/A"}`, 14, y);
      y += 5;
      doc.text(
        `${labels.generatedAt}: ${new Date().toLocaleString()}`,
        14,
        y
      );
      y += 5;
      doc.text(`${labels.generatedBy}: ${user?.name ?? "System"}`, 14, y);
      y += 10;

      // Tier info
      doc.setFont("helvetica", "bold");
      doc.text(`${labels.tierTarget}: Tier ${currentAnalysis.tierTarget}`, 14, y);
      y += 5;
      doc.text(
        `${labels.tierAchieved}: ${currentAnalysis.tierAchieved ? `Tier ${currentAnalysis.tierAchieved}` : "N/A"}`,
        14,
        y
      );
      y += 10;

      // TEDI / TEUI table
      doc.setFont("helvetica", "bold");
      doc.text(labels.complianceAnalysis, 14, y);
      y += 4;

      autoTable(doc, {
        startY: y,
        head: [["Metric", labels.target + " (kWh/m2/yr)", labels.modelled + " (kWh/m2/yr)", labels.gap, "Status"]],
        body: [
          [
            "TEDI",
            String(currentAnalysis.tediTarget),
            String(currentAnalysis.tediModelled),
            String(currentAnalysis.tediGap ?? 0),
            currentAnalysis.tediCompliant ? labels.compliant : labels.nonCompliant,
          ],
          [
            "TEUI",
            String(currentAnalysis.teuiTarget),
            String(currentAnalysis.teuiModelled),
            String(currentAnalysis.teuiGap ?? 0),
            currentAnalysis.teuiCompliant ? labels.compliant : labels.nonCompliant,
          ],
        ],
        didParseCell: (data) => {
          if (data.column.index === 4 && data.section === "body") {
            const isPass = data.cell.raw === labels.compliant;
            data.cell.styles.textColor = isPass ? [22, 163, 74] : [185, 28, 28];
          }
        },
        styles: { fontSize: 9 },
        headStyles: { fillColor: [30, 58, 138] },
      });

      y = (doc as any).lastAutoTable.finalY + 8;

      // Recommendations
      if (currentAnalysis.recommendations?.length > 0) {
        if (y > 240) { doc.addPage(); y = 20; }
        doc.setFontSize(10);
        doc.setFont("helvetica", "bold");
        doc.text(labels.recommendations, 14, y);
        y += 6;
        doc.setFont("helvetica", "normal");
        for (const rec of currentAnalysis.recommendations) {
          const lines = doc.splitTextToSize(`• ${rec}`, pageWidth - 28) as string[];
          if (y + lines.length * 5 > 280) { doc.addPage(); y = 20; }
          doc.text(lines, 14, y);
          y += lines.length * 5 + 2;
        }
        y += 4;
      }

      // Audit trail
      if (y > 240) { doc.addPage(); y = 20; }
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.text(labels.auditTrail, 14, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      doc.text(`${labels.generatedAt}: ${new Date(currentAnalysis.createdAt).toLocaleString()}`, 14, y);
      y += 5;
      doc.text(`${labels.signatureVerified}: ${currentAnalysis.signatureVerified ? "Yes" : "No"}`, 14, y);
      y += 5;
      if (currentAnalysis.cryptographicSignature) {
        doc.text(`Signature: ${currentAnalysis.cryptographicSignature.substring(0, 16)}...`, 14, y);
        y += 5;
      }
      y += 3;

      // Footer reference
      doc.setFontSize(8);
      doc.setTextColor(100, 100, 100);
      doc.text(labels.regulatoryReference, 14, y);

      const filename = `StepCode_Report_${new Date().toISOString().split("T")[0]}.pdf`;
      doc.save(filename);

      // Log to DB
      await saveResult.mutateAsync({
        projectId,
        calculatorType: "stepCodeReport",
        inputData: JSON.stringify({ analysisId: currentAnalysis.id, language }),
        resultData: JSON.stringify({
          reportType: "stepCode",
          tierTarget: currentAnalysis.tierTarget,
          overallCompliant: currentAnalysis.overallCompliant,
          generatedAt: new Date().toISOString(),
          filename,
        }),
      });

      setDidGenerate(true);
      onReportGenerated?.(filename);
    } finally {
      setIsGenerating(false);
    }
  };

  if (isLoading) {
    return <div className="text-center py-8">Loading...</div>;
  }

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5" />
            {labels.title}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <p className="text-sm font-semibold text-muted-foreground">{labels.projectName}</p>
              <p className="text-base">{project?.name || "N/A"}</p>
            </div>
            <div>
              <p className="text-sm font-semibold text-muted-foreground">{labels.address}</p>
              <p className="text-base">{project?.address || "N/A"}</p>
            </div>
          </div>

          {currentAnalysis && (
            <div className="pt-4 border-t">
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-semibold">{labels.complianceAnalysis}</h3>
                <Badge
                  className={
                    currentAnalysis.overallCompliant
                      ? "bg-green-100 text-green-800"
                      : "bg-red-100 text-red-800"
                  }
                >
                  {currentAnalysis.overallCompliant ? labels.compliant : labels.nonCompliant}
                </Badge>
              </div>

              <div className="grid grid-cols-2 gap-4 mb-4">
                <div className="bg-blue-50 p-3 rounded">
                  <p className="text-xs text-muted-foreground">{labels.tierTarget}</p>
                  <p className="text-lg font-bold">Tier {currentAnalysis.tierTarget}</p>
                </div>
                <div className="bg-green-50 p-3 rounded">
                  <p className="text-xs text-muted-foreground">{labels.tierAchieved}</p>
                  <p className="text-lg font-bold">
                    {currentAnalysis.tierAchieved ? `Tier ${currentAnalysis.tierAchieved}` : "N/A"}
                  </p>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4 mb-4">
                {[
                  {
                    label: labels.tediAnalysis,
                    target: currentAnalysis.tediTarget,
                    modelled: currentAnalysis.tediModelled,
                    gap: currentAnalysis.tediGap,
                    compliant: currentAnalysis.tediCompliant,
                  },
                  {
                    label: labels.teuiAnalysis,
                    target: currentAnalysis.teuiTarget,
                    modelled: currentAnalysis.teuiModelled,
                    gap: currentAnalysis.teuiGap,
                    compliant: currentAnalysis.teuiCompliant,
                  },
                ].map((metric) => (
                  <div key={metric.label} className="border rounded p-3">
                    <p className="text-sm font-semibold mb-2">{metric.label}</p>
                    <div className="space-y-1 text-xs">
                      <div className="flex justify-between">
                        <span>{labels.target}:</span>
                        <span className="font-mono">{metric.target} kWh/m²/yr</span>
                      </div>
                      <div className="flex justify-between">
                        <span>{labels.modelled}:</span>
                        <span className="font-mono">{metric.modelled} kWh/m²/yr</span>
                      </div>
                      <div className="flex justify-between">
                        <span>{labels.gap}:</span>
                        <span
                          className={`font-mono ${metric.compliant ? "text-green-600" : "text-red-600"}`}
                        >
                          {metric.gap ?? 0} kWh/m²/yr
                        </span>
                      </div>
                      <div className="flex items-center gap-1 pt-2">
                        {metric.compliant ? (
                          <>
                            <Check className="w-4 h-4 text-green-600" />
                            <span className="text-green-600">{labels.compliant}</span>
                          </>
                        ) : (
                          <>
                            <AlertCircle className="w-4 h-4 text-red-600" />
                            <span className="text-red-600">{labels.nonCompliant}</span>
                          </>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              {currentAnalysis.recommendations?.length > 0 && (
                <div className="bg-yellow-50 p-4 rounded">
                  <h4 className="font-semibold mb-2">{labels.recommendations}</h4>
                  <ul className="space-y-1 text-sm">
                    {currentAnalysis.recommendations.map((rec: string, idx: number) => (
                      <li key={idx} className="flex gap-2">
                        <span className="text-yellow-600">•</span>
                        <span>{rec}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              <div className="bg-gray-50 p-3 rounded text-xs space-y-1 mt-4">
                <p className="font-semibold">{labels.auditTrail}</p>
                <p>{labels.generatedAt}: {new Date(currentAnalysis.createdAt).toLocaleString()}</p>
                <p>{labels.generatedBy}: {user?.name || "System"}</p>
                <p>{labels.signatureVerified}: {currentAnalysis.signatureVerified ? "✓" : "✗"}</p>
              </div>

              <p className="text-xs text-muted-foreground mt-4">{labels.regulatoryReference}</p>
            </div>
          )}
        </CardContent>
      </Card>

      <Button
        onClick={handleGenerateReport}
        disabled={isGenerating || !currentAnalysis}
        className="w-full"
        size="lg"
      >
        <Download className="w-4 h-4 mr-2" />
        {isGenerating ? labels.generating : labels.generateReport}
      </Button>

      {didGenerate && (
        <Card className="bg-green-50 border-green-200">
          <CardContent className="pt-4 pb-4">
            <div className="flex items-center gap-2">
              <Check className="w-5 h-5 text-green-600" />
              <p className="font-semibold text-green-900">{labels.downloaded}</p>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
