import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Download, FileText, Check, AlertCircle } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";

interface StepCodeReportProps {
  projectId: number;
  analysisId: string;
  language?: "en" | "fr";
  onReportGenerated?: (url: string) => void;
}

/**
 * StepCodeReport Component
 * 
 * Generates BC Energy Step Code compliance report in PDF format
 * Bilingual support (EN/FR) for BC projects
 * 
 * Report Contents:
 * - Project information and jurisdiction
 * - Building parameters (area, volume, window-wall ratio)
 * - Step Code tier target and achieved
 * - TEDI/TEUI compliance analysis with visual indicators
 * - Airtightness and mechanical efficiency results
 * - Recommendations for improvement
 * - Professional engineer seal block (for certification)
 * - Immutable audit trail with cryptographic signature
 * - Regulatory references (BC Housing 2017 metrics, NBC 2024)
 * 
 * PD2.0 Compliance:
 * - All data sourced from deterministic rule engine
 * - Cryptographic signature verification
 * - Immutable PDF generation (no post-generation modifications)
 * - Infrastructure logging (user, IP, timestamp)
 */
export function StepCodeReport({
  projectId,
  analysisId,
  language = "en",
  onReportGenerated,
}: StepCodeReportProps) {
  const { user } = useAuth();
  const [isGenerating, setIsGenerating] = useState(false);
  const [reportUrl, setReportUrl] = useState<string | null>(null);

  // Fetch analysis data
  // @ts-ignore
  const { data: analysis, isLoading } = trpc.stepCode.getAnalyses.useQuery({
    projectId,
    limit: 1,
  });

  // Fetch project data
  const { data: project } = trpc.projects.get.useQuery({ id: projectId });

  // Generate PDF report mutation
  // @ts-ignore
  const generateReport = trpc.stepCode.generateReport.useMutation({
    onSuccess: (data: any) => {
      setReportUrl(data.url);
      onReportGenerated?.(data.url);
      setIsGenerating(false);
    },
    onError: () => {
      setIsGenerating(false);
    },
  });

  const handleGenerateReport = async () => {
    if (!analysis || !analysis.length) return;

    setIsGenerating(true);
    await generateReport.mutateAsync({
      projectId,
      analysisId,
      language,
      format: "pdf",
    });
  };

  const currentAnalysis = analysis?.[0];

  // Translation strings
  const t = {
    en: {
      title: "BC Energy Step Code Compliance Report",
      projectInfo: "Project Information",
      projectName: "Project Name",
      address: "Address",
      jurisdiction: "Jurisdiction",
      complianceAnalysis: "Compliance Analysis",
      tierTarget: "Step Code Tier Target",
      tierAchieved: "Tier Achieved",
      compliant: "Compliant",
      nonCompliant: "Non-Compliant",
      tediAnalysis: "TEDI (Thermal Energy Demand Intensity)",
      teuiAnalysis: "TEUI (Thermal Energy Use Intensity)",
      target: "Target",
      modelled: "Modelled",
      gap: "Gap",
      airtightness: "Airtightness (ACH₅₀)",
      mechEfficiency: "Mechanical Efficiency",
      recommendations: "Recommendations for Improvement",
      professionalSeal: "Professional Engineer Seal",
      auditTrail: "Immutable Audit Trail",
      signatureVerified: "Signature Verified",
      generatedAt: "Generated",
      generatedBy: "Generated By",
      generateReport: "Generate PDF Report",
      generating: "Generating...",
      downloadReport: "Download Report",
      regulatoryReference: "Regulatory Reference: BC Housing 2017 Step Code Metrics, NBC 2024",
    },
    fr: {
      title: "Rapport de Conformité du Code d'Énergie de la Colombie-Britannique",
      projectInfo: "Informations sur le Projet",
      projectName: "Nom du Projet",
      address: "Adresse",
      jurisdiction: "Juridiction",
      complianceAnalysis: "Analyse de Conformité",
      tierTarget: "Niveau Cible du Code d'Énergie",
      tierAchieved: "Niveau Atteint",
      compliant: "Conforme",
      nonCompliant: "Non Conforme",
      tediAnalysis: "TEDI (Intensité de la Demande d'Énergie Thermique)",
      teuiAnalysis: "TEUI (Intensité d'Utilisation d'Énergie Thermique)",
      target: "Cible",
      modelled: "Modélisé",
      gap: "Écart",
      airtightness: "Étanchéité à l'Air (ACH₅₀)",
      mechEfficiency: "Efficacité Mécanique",
      recommendations: "Recommandations pour l'Amélioration",
      professionalSeal: "Sceau de l'Ingénieur Professionnel",
      auditTrail: "Piste d'Audit Immuable",
      signatureVerified: "Signature Vérifiée",
      generatedAt: "Généré",
      generatedBy: "Généré par",
      generateReport: "Générer le Rapport PDF",
      generating: "Génération...",
      downloadReport: "Télécharger le Rapport",
      regulatoryReference: "Référence Réglementaire: Métriques du Code d'Énergie 2017 de la Colombie-Britannique, NBC 2024",
    },
  };

  const labels = t[language];

  if (isLoading) {
    return <div className="text-center py-8">Chargement...</div>;
  }

  return (
    <div className="space-y-6">
      {/* Report Header */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5" />
            {labels.title}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Project Information */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <p className="text-sm font-semibold text-muted-foreground">
                {labels.projectName}
              </p>
              <p className="text-base">{project?.name || "N/A"}</p>
            </div>
            <div>
              <p className="text-sm font-semibold text-muted-foreground">
                {labels.address}
              </p>
              <p className="text-base">{project?.address || "N/A"}</p>
            </div>
          </div>

          {/* Compliance Status */}
          {currentAnalysis && (
            <div className="pt-4 border-t">
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-semibold">{labels.complianceAnalysis}</h3>
                <Badge
                  className={
                    currentAnalysis.overallCompliant
                      ? "bg-green-100 text-green-800"
                      : "bg-red-100 text-red-800"
                  }
                >
                  {currentAnalysis.overallCompliant
                    ? labels.compliant
                    : labels.nonCompliant}
                </Badge>
              </div>

              {/* Tier Information */}
              <div className="grid grid-cols-2 gap-4 mb-4">
                <div className="bg-blue-50 p-3 rounded">
                  <p className="text-xs text-muted-foreground">
                    {labels.tierTarget}
                  </p>
                  <p className="text-lg font-bold">
                    Tier {currentAnalysis.tierTarget}
                  </p>
                </div>
                <div className="bg-green-50 p-3 rounded">
                  <p className="text-xs text-muted-foreground">
                    {labels.tierAchieved}
                  </p>
                  <p className="text-lg font-bold">
                    {currentAnalysis.tierAchieved
                      ? `Tier ${currentAnalysis.tierAchieved}`
                      : "N/A"}
                  </p>
                </div>
              </div>

              {/* TEDI/TEUI Results */}
              <div className="grid grid-cols-2 gap-4 mb-4">
                <div className="border rounded p-3">
                  <p className="text-sm font-semibold mb-2">
                    {labels.tediAnalysis}
                  </p>
                  <div className="space-y-1 text-xs">
                    <div className="flex justify-between">
                      <span>{labels.target}:</span>
                      <span className="font-mono">
                        {currentAnalysis.tediTarget} kWh/m²/yr
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span>{labels.modelled}:</span>
                      <span className="font-mono">
                        {currentAnalysis.tediModelled} kWh/m²/yr
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span>{labels.gap}:</span>
                      <span
                        className={`font-mono ${
                          currentAnalysis.tediCompliant
                            ? "text-green-600"
                            : "text-red-600"
                        }`}
                      >
                        {currentAnalysis.tediGap || 0} kWh/m²/yr
                      </span>
                    </div>
                    <div className="flex items-center gap-1 pt-2">
                      {currentAnalysis.tediCompliant ? (
                        <>
                          <Check className="w-4 h-4 text-green-600" />
                          <span className="text-green-600">
                            {labels.compliant}
                          </span>
                        </>
                      ) : (
                        <>
                          <AlertCircle className="w-4 h-4 text-red-600" />
                          <span className="text-red-600">
                            {labels.nonCompliant}
                          </span>
                        </>
                      )}
                    </div>
                  </div>
                </div>

                <div className="border rounded p-3">
                  <p className="text-sm font-semibold mb-2">
                    {labels.teuiAnalysis}
                  </p>
                  <div className="space-y-1 text-xs">
                    <div className="flex justify-between">
                      <span>{labels.target}:</span>
                      <span className="font-mono">
                        {currentAnalysis.teuiTarget} kWh/m²/yr
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span>{labels.modelled}:</span>
                      <span className="font-mono">
                        {currentAnalysis.teuiModelled} kWh/m²/yr
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span>{labels.gap}:</span>
                      <span
                        className={`font-mono ${
                          currentAnalysis.teuiCompliant
                            ? "text-green-600"
                            : "text-red-600"
                        }`}
                      >
                        {currentAnalysis.teuiGap || 0} kWh/m²/yr
                      </span>
                    </div>
                    <div className="flex items-center gap-1 pt-2">
                      {currentAnalysis.teuiCompliant ? (
                        <>
                          <Check className="w-4 h-4 text-green-600" />
                          <span className="text-green-600">
                            {labels.compliant}
                          </span>
                        </>
                      ) : (
                        <>
                          <AlertCircle className="w-4 h-4 text-red-600" />
                          <span className="text-red-600">
                            {labels.nonCompliant}
                          </span>
                        </>
                      )}
                    </div>
                  </div>
                </div>
              </div>

              {/* Recommendations */}
              {currentAnalysis.recommendations &&
                currentAnalysis.recommendations.length > 0 && (
                  <div className="bg-yellow-50 p-4 rounded">
                    <h4 className="font-semibold mb-2">
                      {labels.recommendations}
                    </h4>
                    <ul className="space-y-1 text-sm">
                      {currentAnalysis.recommendations.map((rec: any, idx: number) => (
                        <li key={idx} className="flex gap-2">
                          <span className="text-yellow-600">•</span>
                          <span>{rec}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

              {/* Audit Trail */}
              <div className="bg-gray-50 p-3 rounded text-xs space-y-1 mt-4">
                <p className="font-semibold">{labels.auditTrail}</p>
                <p>
                  {labels.generatedAt}:{" "}
                  {new Date(currentAnalysis.createdAt).toLocaleString()}
                </p>
                <p>
                  {labels.generatedBy}: {user?.name || "System"}
                </p>
                <p>
                  {labels.signatureVerified}:{" "}
                  {currentAnalysis.signatureVerified ? "✓" : "✗"}
                </p>
              </div>

              {/* Regulatory Reference */}
              <p className="text-xs text-muted-foreground mt-4">
                {labels.regulatoryReference}
              </p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Generate Report Button */}
      <Button
        onClick={handleGenerateReport}
        disabled={isGenerating || !currentAnalysis}
        className="w-full"
        size="lg"
      >
        <Download className="w-4 h-4 mr-2" />
        {isGenerating ? labels.generating : labels.generateReport}
      </Button>

      {/* Download Link */}
      {reportUrl && (
        <Card className="bg-green-50 border-green-200">
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="font-semibold text-green-900">
                  {labels.downloadReport}
                </p>
                <p className="text-sm text-green-700">
                  PDF report generated successfully
                </p>
              </div>
              <a
                href={reportUrl}
                download
                className="px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700"
              >
                <Download className="w-4 h-4" />
              </a>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
